### ISSUE TITLE
SPIKE Add OCS and or Ceph Nano for ODH

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/odh-manifests#104]

**Comment by LaVLaS** [comment]
Do we want OCS or a Rook Ceph for this release? OCS has a hard requirement for a 3 node cluster. Rook offers some flexibility for the number of storage nodes

**Comment by guimou** [comment]
Not only 3 nodes, 3 nodes with somewhat lots of resources (16 CPUs/64GB RAM for each node). Also, OCS is through subscriptions only. Is it the first non-"free" component that would be included? If it's the case some adjustments of ODH positioning may be required.

**Comment by LaVLaS** [comment]
Based on @guimou comments, that means we would fall back to Rook for providing the object storage. We would need to include a base for the default 3 node storage and an overlay for a possible minimal/dev install with one node

**Comment by guimou** [comment]
Based on a discussion with Daniel Riek 10 minutes ago in the AI ILT wkg, both options should be available depending on the environment. So base and overlays, or maybe only overlays, as people could want to use directly AWS S3 for example if that's were ODH is deployed.

**Comment by LaVLaS** [comment]
We can have follow up discussions on AI ILT wkg topics internally. For `odh-manifests`, we will attempt to add Rook Ceph as an object storage component. Due to the RH subscription requirement, OCS will have to be a separate deployment outside of ODH manifests.
