### ISSUE TITLE
Use OpenShift OAuth with Grafana 

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/odh-manifests#106]
We should update the [Grafana resource](https://github.com/opendatahub-io/odh-manifests/blob/master/grafana/grafana/base/grafana.yaml) to match the functionality we provided in version <0.6

The example from grafana-operator repo: https://github.com/integr8ly/grafana-operator/blob/v3.2.0/deploy/examples/oauth/Grafana.yaml
ETA 1 month

**Comment by anishasthana** [comment]
I can work on it as part of the grafana upgrade to 3.5
