### ISSUE TITLE
integrate FDE notebooks image into odh

### ISSUE THREAD

**Issue by goern** [opendatahub-io/odh-manifests#111]
FDE would like to integrate the notebook published on quay into ODH, so that they can be used by any OHD user

**Comment by vpavlin** [comment]
Ok, how can we help?

**Comment by durandom** [comment]
Please guide how to add the notebooks to the default JH configmap, which I guess is where the list of avail images is maintained. So that these images are avail in the dropdown...

**Comment by vpavlin** [comment]
The images are deployed as ImageStreams. All the IS are in https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images

The default are in `base`, additional are in `overlays` and then subdirs. 

I am not sure what is special about these images or what the purpose is, so not sure if it should simply go to `additional` overlay, or if it needs a new one

**Comment by goern** [comment]
It sounds to me that we should create and FDE overlay, so that we have all notebooks maintained by FDE in one place and we can decide to deploy them or not in a very simple way.

**Comment by goern** [comment]
@AICoE/FDE

**Comment by vpavlin** [comment]
After a discussion with @pacospace, we agreed to start with providing some documentation:

* [ ] https://github.com/opendatahub-io/odh-manifests/issues/113
* [ ] https://github.com/opendatahub-io/odh-manifests/issues/114

**Comment by willb** [comment]
Thanks for the docs!  If we can contribute our notebook images as an ODH component it will make it a lot easier for community members to reproduce our work.
