### ISSUE TITLE
Security constraints to enable PNS executor for KF on OpenShift

### ISSUE THREAD

**Issue by panbalag** [opendatahub-io/odh-manifests#117]
I ran in to the following issue while trying to run KF pipelines on OpenShift
https://github.com/kubeflow/pipelines/issues/1654

The recommended solution was to switch to PNS executor along with the following constraints. Is this allowed under ODH/OpenShift security guidelines?
---------------------------------------------------------------------------------------------------------------------------------------
oc adm policy add-scc-to-user privileged kubeflow:pipeline-runner
oc adm policy add-scc-to-group anyuid kubeflow:pipeline-runner
kubectl create clusterrolebinding pipeline-runner-extend --clusterrole cluster-admin --serviceaccount=kubeflow:pipeline-runner

Also, if the OpenShift master is set up with privileged is required for P_TRACE, then we also need to add the following methods to all the containerOp.

.set_security_context(V1SecurityContext(privileged=True))
-----------------------------------------------------------------------------------------------------------------------------------------

**Comment by nakfour** [comment]
@panbalag we don't use PNS we use "k8sapi", we avoid running privileged tasks, does PNS need root access?

**Comment by panbalag** [comment]
@nakfour   KF pipelines does not work with k8sapi so I was recommended to test with PNS executor. I'm not sure about the root access. Any ideas on how I can test it?

**Comment by nakfour** [comment]
@panbalag I tried PNS executor and the first issue I encountered is 
```

pods "hello-world-nkhjq" is forbidden: unable to validate against any security context constraint: [capabilities.add: Invalid value: "SYS_PTRACE": capability may not be added]
```
the only way around this is to give the container a privileged run which is not recommended. Is it possible to try keep "ks8api" and try to set the volume parameters are explained here: https://github.com/kubeflow/pipelines/issues/1654
```
output_artifact_paths={
  'mlpipeline-ui-metadata': '/output/mlpipeline-ui-metadata.json',
  'mlpipeline-metrics': '/output/mlpipeline-metrics.json',
}
```
