### ISSUE TITLE
Test ODH deployment on OKD and CRC

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-manifests#161]
We need to verify that ODH can deploy successfully on OKD and CRC with steps for a successful deployment under the assumption the deployment process is simple and the user just needs to configure cluster resources.

* [x] OKD
* [x] CRC

**Comment by vpavlin** [comment]
@LaVLaS I've tried to deploy ODH on OKD 4.5 and it worked without any issues. I think we might want to consider OKD as a test platform in the future

**Comment by LaVLaS** [comment]
CRC deployment has been successful for me provided we increase the cpu and memory specs for the cluster prior to deployment.

**Comment by stobias123** [comment]
@vpavlin  - which manifests are you using for deployment? I'm not sure which manifest is the "default" and should be used.
