### ISSUE TITLE
GPU notebook builds are getting failed

### ISSUE THREAD

**Issue by altruistcoder** [opendatahub-io/odh-manifests#167]
I am working on a project for which I have a need to create some tensorflow & GPU based notebook images for my odh project.
I am facing the below issue while running the build of my "minimal-notebook".

The error as shown in the logs is:

```
Successfully built supervisor
Installing collected packages: meld3, supervisor
Successfully installed meld3-2.0.1 supervisor-3.3.5
WARNING: You are using pip version 20.2.1; however, version 20.2.2 is available.
You should consider upgrading via the '/opt/app-root/supervisor/bin/python -m pip install --upgrade pip' command.
/tmp/scripts/assemble: line 148: jupyter: command not found
subprocess exited with status 127
subprocess exited with status 127
error: build error: error building at STEP "RUN /tmp/scripts/assemble": exit status 127
```

I checked this is happening with both the **ODH 0.5.1** as well as **ODH 0.7.0** versions. The Cuda-Build-Chain is failing in both the cases. 

For creating the "**s2i-minimal-notebook-gpu**" image, I am using **https://github.com/vpavlin/jupyter-notebooks/tree/feature/add-tf-gpu/minimal-notebook** as the source code repository and "**python-36-ubi7**" as the base image which itself is built using this **https://github.com/sclorg/s2i-python-container/tree/master/3.6** as the source code repo.

A similar issue has been reported here **https://github.com/vpavlin/jupyter-notebooks/issues/16** and here **https://gitlab.com/opendatahub/opendatahub-operator/-/issues/235** as well, but not able to understand its solution clearly.

Can you please tell me how you solved this error and provide me some fix as I am stuck  on this. It would be really very very helpful.

@vpavlin @pdmack @LaVLaS @nakfour @harshad16 @crobby @goern

**Comment by pdmack** [comment]
https://gitlab.com/opendatahub/opendatahub-operator/-/issues/235

**Comment by vpavlin** [comment]
Hi @altruistcoder, we are investigating this issue (see https://gitlab.com/opendatahub/opendatahub-operator/-/issues/235). @LaVLaS any luck with your experiments?

**Comment by altruistcoder** [comment]
Hii @vpavlin ,

I came to know from Pete that you have a branch **bug/gpu-jupyter-missing**  in this repository: **https://github.com/vpavlin/jupyter-notebooks** which is seems to be a fix for this. I tried this and it worked fine for me and I was able to create my "**s2i-minimal-notebook-gpu**". Now, I want to create "**s2i-minimal-lab-notebook-gpu**" notebook image as well. 
So, do you have any source code similar to "minimal-notebook" for creating an image for jupyter-lab as well?

@pdmack @LaVLaS @harshad16 @crobby

**Comment by vpavlin** [comment]
I would not call that branch a fix, it is mostly a workaround/hack to get the build running:)

Regarding the Lab, if you give me a couple days I will have that image for you available - I am just in the middle of getting JupyterLab working in ODH

**Comment by altruistcoder** [comment]
Okay, ya I get that. 

That would be great if the images for the labs would be available. 
Also, Is there some documentation present somewhere which I can refer to gain better understanding on how the build-chain has been created and how we can create all these hierarchy of images from cuda to tensorflow-gpu-notebook?

**Comment by goern** [comment]
@harshad16 @sub-mod

**Comment by altruistcoder** [comment]
Hello @vpavlin,

I wanted to share one more observation with you. Actually, I was able to create all the images successfully using the "**cuda-build-chain**" earlier around mid April. But, now when we are trying to build it again we are getting the error stated above. 

I saw that the source code of the [cuda](https://github.com/sub-mod/cuda/blob/ubi7/10.0) repository and your [minimal-notebook](https://github.com/vpavlin/jupyter-notebooks/tree/master/minimal-notebook) repository haven't got any commits after April. Only the [python](https://github.com/sclorg/s2i-python-container/tree/master/3.6) repository has undergone multiple changes since then. I also tried using some of the older commits of the python repository but that also doesn't seem to work. 
Do you have any idea as to why are we getting this error even when we use the unmodified source code.

**Comment by vpavlin** [comment]
Hi @altruistcoder 

Sorry for late response. Finally got to this and hit a roadblock with https://github.com/opendatahub-io/odh-manifests/issues/209

@harshad16 is looking into it, once it is resolved, I'll get back to this one

**Comment by vpavlin** [comment]
Hi @altruistcoder! Can you try to deploy using master of odh-manifests? We got the cuda build chain update and the build succeeded for me and I was able to start the TF GPU notebook image

**Comment by altruistcoder** [comment]
Hii @vpavlin,

Thanks for providing a solution to this problem. I was able to build the tensorflow image and the **cuda build chain** using the [cuda-ubi7-build-chain.yaml](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml) and [tensorflow-gpu-notebook.yaml](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/tensorflow-gpu-notebook.yaml) files.

But, still I believe that deploying the cuda build chain from the Kfdef file itself doesn't work when we specify the following in the KfDef:

```
- kustomizeConfig:
    overlays:
      - additional
      - cuda
    repoRef:
      name: manifests
      path: jupyterhub/notebook-images
  name: notebook-images
```

I see the following error when building the cuda chain:

```
Cloning "https://github.com/harshad16/cuda.git" ...
error: fatal: Couldn't find remote ref ubi7
Unexpected end of command stream
```

**Comment by harshad16** [comment]
It feels like the deployment is still using the old `cuda-build-chain` ! updated manifest is required.

**Comment by altruistcoder** [comment]
Yes, I also feel the same. 

I wanted to ask one more thing. 
Can you please provide some suggestions on how can I create jupyter lab images instead of jupyter notebooks images. I tried adding the **JUPYTER_ENABLE_LAB=true** in the `minimal-notebook/.s2i/environment.txt` file in this [repo](https://github.com/vpavlin/jupyter-notebooks/tree/feature/add-tf-gpu), but I got the following error while spawning the **minimal-notebook-image**:


```
/usr/bin/container-entrypoint: line 2: /opt/app-root/bin/start-singleuser.sh: Permission denied
/usr/bin/container-entrypoint: line 2: exec: /opt/app-root/bin/start-singleuser.sh: cannot execute: Permission denied
```

So, if you could please share some resolution for this (if you ever faced this problem too) or tell me some way to build jupyter lab images instead of jupyter notebook images, then that would be really very helpful.

@vpavlin @harshad16

**Comment by harshad16** [comment]
@altruistcoder , sorry for the delayed response, I need to work on checking my notifications properly.
anyway regarding the use of jupyter lab in the s2i-minimal-notebook.
is the requirement to create an image? or just to use the jupyter lab from s2i-minimal-notebook?
- if it is to use the jupyter lab in the s2i-minimal-notebook, then jupyter lab is already existing in the [image](https://quay.io/repository/thoth-station/s2i-minimal-notebook?tab=tags) to use.
`podman run -it -p 8888:8888 quay.io/thoth-station/s2i-minimal-notebook:latest jupyter lab` 
- if you would like to tweak something and want to create separate image.
This repository can be used, https://github.com/thoth-station/s2i-minimal-notebook 
as of now, we are having version 2.2.4 jupyter lab in our s2i-minimal-notebook image. 

Hope this help, please let us know if anything else is required.

About the cuda build error, were you able to update the manifest file in your odh deployment and retest it ?

**Comment by altruistcoder** [comment]
@harshad16 I haven't tried to retest it after updating the manifest file in my odh deployment yet but I am surely going to do that. Although, I have already tested building the cuda chain using [cuda-ubi7-build-chain.yaml](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml) and [tensorflow-gpu-notebook.yaml](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/tensorflow-gpu-notebook.yaml) files manually. 

Also, I tried to create a separate image of the **s2i-minimal-lab-notebook** using the repository provided by you but I am getting some error and I can see the following in the logs of the build:

```
 -----> Creating additional directories.
+ mkdir -p /opt/app-root/data
+ sed -e 's%^logfile=/tmp/supervisord.log%logfile=/dev/fd/1%' -e 's%^logfile_maxbytes=50MB%logfile_maxbytes=0%'
+ echo_supervisord_conf
/tmp/scripts/assemble: line 87: echo_supervisord_conf: command not found
subprocess exited with status 127
subprocess exited with status 127
error: build error: error building at STEP "RUN /tmp/scripts/assemble": exit status 127
```

**Comment by harshad16** [comment]
@altruistcoder can you provide some more details, like which base image did you use to build the image and as such.
so that we can try to re-create the issue.

**Comment by altruistcoder** [comment]
@harshad16 I followed exactly the yaml file present [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml) and used the base image and the repositories specified in this yaml file to create the `python-36-ubi7` image and then used this python image to create the `s2i-minimal-lab-notebook` image using the repository specified by you above which is this one [here](https://github.com/thoth-station/s2i-minimal-notebook).

**Comment by vpavlin** [comment]
Hmm..I don't think I have seen this before. Can you share actual steps to reproduce this?

**Comment by altruistcoder** [comment]
Okay, following are the steps to reproduce the issue:

1. First, I created two imagestreams for `cuda` and `python-36-ubi7` image using the yaml codes provided [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml#L3) and [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml#L13).
2. Then, I created the `cuda:10.1-base-ubi7` image using `registry.access.redhat.com/rhscl/s2i-base-rhel7:1` as the base image and using the BuildConfig present [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml#L23).
3. Next, created the `cuda:10.1-runtime-ubi7` image using `cuda:10.1-base-ubi7` as the base image and using the BuildConfig present [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml#L66).
4. The, created the `cuda:10.1-cudnn7-runtime-ubi7` image using `cuda:10.1-runtime-ubi7` as the base image and using the BuildConfig present [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml#L104).
5. Next, created the `cuda:10.1-devel-ubi7` image using `cuda:10.1-runtime-ubi7` as the base image and using the BuildConfig present [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml#L142).
6. And then, created the final cuda image, i.e. `cuda:10.1-cudnn7-devel-ubi7` image using `cuda:10.1-devel-ubi7` as the base image and using the BuildConfig present [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml#L180).
7. After that, I created the `python-36-ubi7:latest` image using `cuda:10.1-cudnn7-devel-ubi7` as the base image and using the BuildConfig present [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml#L218).

Finally for creating the `s2i-minimal-lab-notebook:3.6` image, I used this `python-36-ubi7:latest` image created above as the  base image and this [repository](https://github.com/thoth-station/s2i-minimal-notebook) (which was shared by Harshad above) as the source code repository. I have attached below, the BuildConfig file I created in this step, for your reference: 
[s2i-minimal-lab-notebook-gpu-build-config.txt](https://github.com/opendatahub-io/odh-manifests/files/5483221/s2i-minimal-lab-notebook-gpu-build-config.txt)

**Comment by altruistcoder** [comment]
Also, I had one more requirement. I was thinking to have **Elyra** also present in the **tensorflow-gpu-notebook** image so if possible can you please provide the source code repository using which you have created the Elyra lab notebook image. 

I found the already built image here: [quay.io/thoth-station/s2i-lab-elyra:v0.0.2](quay.io/thoth-station/s2i-lab-elyra:v0.0.2) but as described this won't fulfill my current requirement of having elyra present in the tensorflow-gpu-notebook image itself.

**Comment by harshad16** [comment]
@altruistcoder , I found the reason why the issue is occurring while building s2i-minimal-notebook. 
we just need to enable **pipenv** or **micropipenv**(python package dependencies managers) in the s2i buildconfig during the process. 
Add the following environment variable to the build config you shared.
```
    env:
      - name: ENABLE_PIPENV
        value: "1"
      - name: UPGRADE_PIP_TO_LATEST
        value: "1"
```

Here is the buildconfig: 
```
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: s2i-minimal-lab-notebook-gpu
  labels:
    build: s2i-minimal-lab-notebook-gpu
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 's2i-minimal-lab-notebook-gpu:3.6'
  resources:
    limits:
      memory: 4Gi
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'python-36-ubi7:latest'
    env:
      - name: ENABLE_PIPENV
        value: "1"
      - name: UPGRADE_PIP_TO_LATEST
        value: "1"
  source:
    type: Git
    git:
      uri: 'https://github.com/thoth-station/s2i-minimal-notebook'
  triggers:
    - type: ConfigChange
    - type: ImageChange
```

Do let me know if you still face any issue with this.

About the elyra, 
once the s2i-minimal-lab-notebook-gpu image is built you can create another buildconfig to build this git repo https://github.com/opendatahub-io/s2i-lab-elyra with the s2i-minimal-lab-notebook-gpu  
that should get you a elyra based image.

**Comment by altruistcoder** [comment]
@harshad16, Thanks for providing this solution. I was able to successfully create the s2i-minimal-lab-notebook-gpu image by adding these environment variables in the respective BuildConfig, but I am still able to see the **"tree"** view of the notebook only when it gets spawned by any user by default. Although we can switch to **"Lab"** view by modifying the URL from `/tree` to `/lab`, but I want to have the lab view by default when any user spawns this particular image from the JupyterHub. Can you please guide me how can I achieve this?

Also, I have one more general query,

Whenever newer versions of ODH releases, would we need to manually upgrade all the instances (which were created using ODH Operator of Openshift) to the newer version or is it going to happen automatically? For example, right now we have several instances running with ODH instances of 0.8.0 version. So, how can we upgrade them to newer version of ODH as the newer version  of ODH might contain newer versions of its constituent components such as spark, seldon, prometheus, etc., (ofcourse without affecting the running workloads) ?

**Comment by harshad16** [comment]
@altruistcoder , great to know, the GPU image build issues are all resolved.
Regarding the other question you have asked, I m not fully aware of all these, but I would try to answer with the best of my knowledge.
To have the jupyterlab as default in jupyterhub, we might have to define that in the jupyterhub_config.yaml.
check here: https://jupyterlab.readthedocs.io/en/stable/user/jupyterhub.html
https://github.com/opendatahub-io/odh-manifests/blob/6dfa8be0d4ad08712518b32640c9d3f95bc00549/jupyterhub/jupyterhub/base/jupyterhub-configmap.yaml

and as of know user would have to manually-update the odh deployment from v0.8.0 to v0.9.0 (but i m not sure)

@vpavlin and @LaVLaS  might be a better people here to guide you regarding these.

Thanks for the patience .

**Comment by vpavlin** [comment]
> I want to have the lab view by default

You can have `JUPYTER_ENABLE_LAB` set to `1` or `true` for the users in the image which will automatically enable the lab UI

see https://github.com/thoth-station/s2i-minimal-notebook/blob/master/start-notebook.sh#L30

For the update, I believe our operator is set to auto-update, but you would still need to change the KFDef custom resource to get new manifests deployed - you will need to update the repo URL when a new release is cut - e.g. https://github.com/opendatahub-io/odh-manifests/blob/v0.9-branch/kfdef/kfctl_openshift.yaml#L122

**Comment by vpavlin** [comment]
We are also planning on bringing the classic notebook vs. lab option as a switch in Spawner UI in the future.

**Comment by altruistcoder** [comment]
So, if there comes an update in the version of one of the components of ODH (for example Seldon) in the release of a new version of ODH, then the instances running with older version of ODH will be having the older version of that particular component and we will have to upgrade them manually for now, right?

And, that sounds really interesting to have a switch option between the classic notebook and its lab view. I'll be looking forward to that.

Also, I need one more help. I was trying to modify & add some of the python dependencies in the `s2i-tensorflow-notebook` image built using the BuildConfig specified [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/tensorflow-gpu-notebook.yaml#L56) which uses the source code repository present [here](https://github.com/thoth-station/s2i-tensorflow-notebook). I updated the `requirements.in` with my required dependencies and used the same for building the `s2i-tensorflow-notebook` image, but the change I made in the dependencies didn't got reflected in the actual image thus formed. I think I am not making changes for my dependencies at the correct location as it should be made in but I am not so sure about this.
Can you please help in finding a solution to this problem?

**Comment by harshad16** [comment]
> Also, I need one more help. I was trying to modify & add some of the python dependencies in the `s2i-tensorflow-notebook` image built using the BuildConfig specified [here](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/tensorflow-gpu-notebook.yaml#L56) which uses the source code repository present [here](https://github.com/thoth-station/s2i-tensorflow-notebook). I updated the `requirements.in` with my required dependencies and used the same for building the `s2i-tensorflow-notebook` image, but the change I made in the dependencies didn't got reflected in the actual image thus formed. I think I am not making changes for my dependencies at the correct location as it should be made in but I am not so sure about this.
> Can you please help in finding a solution to this problem?

@altruistcoder , you can update the python packages in the Pipfile (with [pipenv](https://github.com/pypa/pipenv)). As in the build config we are enabling pipenv install which makes the build process to consider the python packages listed in the pipfile. 
This should fix your issue.
Ex: `pipenv install example`

**Comment by vpavlin** [comment]
Can we close this? There has been many changes in the CUDA builds, so I assume they work now?

**Comment by altruistcoder** [comment]
Yes, a lot of thanks to you @vpavlin and @harshad16 for helping in solving this issue and all the sub-issues specified within this one.  
Really appreciated!!
