### ISSUE TITLE
Talk with Red Hat CPaaS team to identify any tooling and processes we can reuse for the pipelines that are already used for Red Hat products.

### ISSUE THREAD

**Issue by shgriffi** [opendatahub-io/odh-manifests#168]
Jeff Burke recommended we start with https://gitlab.cee.redhat.com/cpaas/documentation.  It has enough information for us to evaluate how we can plug into their process.

**Comment by crobby** [comment]
Starting with:  https://gitlab.cee.redhat.com/cpaas/documentation/-/blob/master/users/getting_started.adoc
Other docs found here: https://gitlab.cee.redhat.com/cpaas/documentation
