### ISSUE TITLE
Separate test runner from test code

### ISSUE THREAD

**Issue by crobby** [opendatahub-io/odh-manifests#174]
In an effort to be able to reuse our testing infra in other repositories without having to maintain seprate copies of our source code, this card is mean to separate the "boilerplate" test running code from the tests themselves.

This is just my initial set of ideas.  2a/2b may or may not make sense/be desirable.  Feedback is great.

1) Create a new repo that will house the source for the base ODH testing image

2a) Ensure that all of the "test content" [env, source, resources, whatever is needed to test any given repo] can be provided via environment vars (test bits may need to be cloned or mounted at runtime) to the ODH testing image at runtime.  

2b) Make it such that the ODH testing image can be used as a base image and a given repo/user could extend the base image to produce a "full image" that includes their repo-specific testing bits that can be ran either in the openshift-ci system or as a standalone image against any OpenShift cluster.

3) Update documentation so that it's clear how the updated test suite can be ran.

**Comment by crobby** [comment]
@vpavlin I tried to capture our brief discussion.  Thoughts?

**Comment by crobby** [comment]
I just took a look at the latest in:  https://github.com/AICoE/peak  @tmckayus has pushed s2i functionality that will grab the tests from your repo and make an image that will run those tests.  Ideally, we can piggyback off that, but it does seem that we would need to make a few more adjustments, probably both to the peak utility as well as our test runner structure (especially the install/create KfDef CRD parts).  Maybe it's just a matter of us overriding the default command so that we trigger our own installer/setup scripts.

**Comment by tmckayus** [comment]
@crobby happy to help make any mods you might need

**Comment by tmckayus** [comment]
We're going to try adding a "-e" env var to the s2i build to name a startup script (relative path within the source)  to be run before run.sh is invoked. As long as that file does not end in .sh, run.sh will not treat it as a test file.

As a second pass, we might add a mechanism for marking even a .sh file as "ignore for tests"
