### ISSUE TITLE
Kubeflow Pipelines with Tekton on OpenShift

### ISSUE THREAD

**Issue by animeshsingh** [opendatahub-io/odh-manifests#190]
We are able to run Kubeflow Pipelines with Tekton on OpenShift. We are installing our own Tekton (v0.14) 
https://github.com/IBM/KubeflowDojo/blob/master/OpenShift/manifests/README.md

OpenShift Pipelines has released OpenShift Pipelines v1.1 which contains Tekton v0.14 and Triggers v0.6 in tech preview on OpenShift 4.5. Since we don't have OpenShift 4.5 currently, we are looking at best way to get that going.
.

**Comment by animeshsingh** [comment]
cc @vpavlin @nakfour

**Comment by vpavlin** [comment]
That sounds awesome. I am going to test this on OpenShift 4.5 by the end of the week and let you know.

@adrian555 Will you have time/Would you like to submit a PR for odh-manifests to add KFP on Tekton as a component?

**Comment by adrian555** [comment]
@vpavlin I would love to. The only catch is our kfp-tekton manifests are in kustomize v3 while the odh-manifests are not. The current operator (hence the `kfctl`) can't handle the mix of two. Do you have a plan/timeline to move up odh-manifests to v3 format?
