### ISSUE TITLE
Enable Oauth for superset

### ISSUE THREAD

**Issue by maulikjs** [opendatahub-io/odh-manifests#193]
Right now we dont have any authentication for superset except the admin user. It would be nice to have oauth support for superset so we can integrate it at the enterprise scale.
Currently, I am using LDAP but OAUTH will be a much more seamless experience across all other ODH components.

**Comment by tumido** [comment]
Hi team, is there any plan on implementing this? We would greatly benefit from this feature in OperateFirst, since we don't have any LDAP available and all our auth can rely on OIDC/OAuth only.

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
