### ISSUE TITLE
ODH installation Problem on Openshift Cluster

### ISSUE THREAD

**Issue by vimalsehal** [opendatahub-io/odh-manifests#197]
I created one new openshift cluster version 4.5.9 on AWS and installed ODH 0.8 operator. I tried to create its instance but got failed with error. Please refer to error details in attached file. First thought was may be some regression problem with latest openshift version. I uninstalled and switched to 4.5.7 but again same error. Though i am able to create instance of ODH 0.5.2 legacy option provided in operator and its working fine. 

It looks like unable to download tarball and error related to kubeflow.error.

Could you please help me to resolve this issue, my work is already delayed by couple of days because of this issue. I did the same ODH0.8 installation on another existing openshift cluster 4.5.7 and it was working fine. Not sure the issue with this new openshift cluster on AWS.
[error_msg.txt](https://github.com/opendatahub-io/odh-manifests/files/5265721/error_msg.txt)

**Comment by crobby** [comment]
@vimalsehal 
That error does seem to be a problem when trying to resolve the manifest tarball at:  https://github.com/opendatahub-io/manifests/tarball/v1.0-branch-openshift
We've seen that before if github is having issues or if your server is having trouble hitting github.  If the problem persists, can you open a terminal inside the opendatahub-operator pod/container and try the following command:
`curl -L https://github.com/opendatahub-io/manifests/tarball/v1.0-branch-openshift --output test.tar`
If that fails, then there is likely some network connectivity issue with your cluster.

**Comment by vimalsehal** [comment]
Thanks @crobby for the quick response, really appreciate.
I tried as you suggested and i am able to download the file with the help of curl in terminal of opendatahub-operator pod in openshift-operators namespace.
I have tar file now in the folder(/tmp/<project-name>/opendatahub/.cache/kf-manifests) though unable to untar it. So looks like network connectivity is good.
Please advise.

**Comment by crobby** [comment]
@vimalsehal
Is there any chance that proxy is in use?  I think there is a PR open right now that might help that situation, but it's not yet verified.

Maybe try deleting your KfDef `oc delete kfdef <your kfdef name>` and the recreating it.  That would cause the operator to try downloading again.  See if you get the same error message in the operator log.

**Comment by vimalsehal** [comment]
Thanks @crobby for the response.
Yes I tried many times deleting Kfdef and recreating it, but problem still persist. it is unable to download.
Please advise.

**Comment by crobby** [comment]
@vimalsehal 
I don't have any other ideas at the moment.  We have marked this as a bug, but I'm not sure that anyone on our team has found a way to reproduce this yet.  Can you give us full set of steps (including your Openshift cluster creation steps) so that we can reliably reproduce this issue?

**Comment by crobby** [comment]
Be sure to include the KfDef that you're attempting to create as well.  Based on the contents of that, we might have a few more things to try.

**Comment by vimalsehal** [comment]
Thanks @crobby for the response.
We are using the complete KfDef given as default. We also tried with shorter version as per our requirement. But error is same in case of default / altered KfDef.

Please find attached document for steps involved in cluster set-up.
[Cluster Installation Steps.docx](https://github.com/opendatahub-io/odh-manifests/files/5303316/Cluster.Installation.Steps.docx)

**Comment by LaVLaS** [comment]
@vimalsehal As a test to see if the operator is failing to handle a http redirect properly, can you change the kfdef repo uri to `https://codeload.github.com/opendatahub-io/manifests/legacy.tar.gz/v1.0-branch-openshift`?

**Comment by vimalsehal** [comment]
> @vimalsehal As a test to see if the operator is failing to handle a http redirect properly, can you change the kfdef repo uri to `https://codeload.github.com/opendatahub-io/manifests/legacy.tar.gz/v1.0-branch-openshift`?

@LaVlas thanks for you help. I tried above uri but still the same issue.

**Comment by vimalsehal** [comment]
> Hey @vimalsehal...we have seen this issue in the past: [kubeflow/kfctl#167 (comment)](https://github.com/kubeflow/kfctl/issues/167#issuecomment-573170978)
> 
> The person who reported it to us back then was able to workaround the issue by uploading the manifest tarball to AWS S3 and change the repo URL - can you try that?
> 
> This issue should be solved though and it seems we cannot reproduce your issue on OpenStack or AWS clusters that we have access to.

@vpavlin Thanks for your help. I put both files mentioned in Kfdef(giving problem for both) on S3 and its worked. Looks like some issue with Github because CURL was working for Github  and now it was able to download the same files from S3. I am able to proceed further. Thanks again for your support Cheers!.
