### ISSUE TITLE
Add ISSUE_TEMPLATE and PULL_REQUEST templates to enable github workflow

### ISSUE THREAD

**Issue by kshithijiyer** [opendatahub-io/odh-manifests#198]
To enable the project for a GitHub bases workflow we would need to add:

1. ISSUE_TEMPLATE
2. PULL_REQUEST_TEMPLATE

These templates would be helpful for us to structure the issues we get which could be bugs, RFEs, or other kinds of requests, and the PRs which get according to a set structure making it easy to review in case PRs and easy to RCA in case of Issues.

**Comment by nakfour** [comment]
@kshithijiyer yes we have a PR for it #201

**Comment by kshithijiyer** [comment]
Oh okay
