### ISSUE TITLE
Prometheus ServiceMonitors for ODH components

### ISSUE THREAD

**Issue by 4n4nd** [opendatahub-io/odh-manifests#216]
**Is your feature request related to a problem? Please describe.**
Currently I can see a Prometheus ServiceMonitor manifest just for [Kafka](https://github.com/opendatahub-io/odh-manifests/blob/master/prometheus/operator/base/kafka-servicemonitor.yaml). There are other odh components (like jupyterhub) that do not have a servicemonitor. Do other services not need a servicemonitor?

**Describe the solution you'd like**
Create servicemonitors for other components.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by 4n4nd** [comment]
cc @anishasthana

**Comment by anishasthana** [comment]
I think it's definitely something we'd need to add. I think the Op 1st work and the migration to ocp4 for our team will give us plenty of opportunities to write new ones

**Comment by 4n4nd** [comment]
Created a PR for JH servicemonitor: https://github.com/opendatahub-io/odh-manifests/pull/239
