### ISSUE TITLE
Generic Grafana dashboards for ODH components

### ISSUE THREAD

**Issue by hemajv** [opendatahub-io/odh-manifests#218]
**Is your feature request related to a problem? Please describe.**
Currently, I see some sample Grafana dashboards available for a few ODH components such as [Argo.](https://github.com/opendatahub-io/odh-manifests/blob/master/grafana/grafana/base/argo-dashboard.yaml) 
Are there plans to include dashboards for other components as well?

**Describe the solution you'd like**
Create generic Grafana dashboard templates for other components such as JupyterHub, Kafka etc.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by nakfour** [comment]
@hemajv we try to add dashboards for different components, however we don't have a plan today to include all components. If you have any Grafana dashboards you would like to submit please open a PR.

**Comment by hemajv** [comment]
@nakfour thanks for the quick reply! We will be working on this as part of our [Operate First](https://github.com/operate-first) efforts and share the dashboards once we have them ready.
