### ISSUE TITLE
Jupyter Enterprise Gateway integration in ODH?

### ISSUE THREAD

**Issue by pacospace** [opendatahub-io/odh-manifests#220]
**Is your feature request related to a problem? Please describe.**

As Data Scientist on Elyra [1],

I want to run an AI pipeline with different runtime environments for each step, using container images generated by aicoe-ci and so that the software stack of the container image has been recommended by Thoth [2].

Some steps might require Spark, other CPU, and other GPU. These different requirements might not be available on the same cluster where ODH is deployed. Therefore there should be a need for remote kernel access from notebooks to external clusters with the resources requested.

Not sure how this would work with the different types of frameworks for pipelines (Argo, Kubeflow, Tekton) or if some solution is already available in Elyra. 

**Describe the solution you'd like**
Is there a plan to include Jupyter Enterprise Gateway [3]?

For example, if you have a pipeline with the last step after testing deployment, which is deployed on another cluster which has some specific requirements. The image to run there can be optimized by an optimizing deployment pipeline [2] and the use there. 

**Describe alternatives you've considered**

**Additional context**
[1] https://github.com/elyra-ai/elyra
[2] https://github.com/thoth-station
[3] https://github.com/jupyter/enterprise_gateway

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
