### ISSUE TITLE
Update the manifests to use the new strimzi operator (v0.20.0)

### ISSUE THREAD

**Issue by crobby** [opendatahub-io/odh-manifests#225]
**Is your feature request related to a problem? Please describe.**
Version v0.20.0 of the strimzi operator seems to have updated the CRD so that our Kafka CR (version 2.4.0) is no longer supported.  To use the new version, we will need to update our Kafka CR as well.

**Describe the solution you'd like**
Update our subscription to use the v0.20.0 channel and update our Kafka CR so that it will work with the new operator.

**Comment by guimou** [comment]
While waiting for this to happen, will the pinning of Strimzi to 0.19 that you pushed in master be backported to 0.8? Because meanwhile 0.8 is broken when you let it deploy Strimzi by itself...
