### ISSUE TITLE
Unable to deploy CUDA notebook overlays

### ISSUE THREAD

**Issue by carlmes** [opendatahub-io/odh-manifests#232]
**Describe the bug**
When performing a new installation on a GPU enabled OpenShift environment, we get the following error message:

```
message: |
            Cloning "https://github.com/harshad16/cuda.git" ...
            error: fatal: Couldn't find remote ref ubi7
            Unexpected end of command stream
```

![unnamed](https://user-images.githubusercontent.com/10638247/98168218-7cf90b80-1ea7-11eb-874d-3d8968a647bc.png)

**Steps To Reproduce**
1. Follow the instructions in the tutorial: https://github.com/DanielFroehlich/stormshift/blob/master/docs/GPU-DEMO.md
2. The build failure occurs right after creating the KFDef.

**Expected behavior**
Expect the cuda enabled notebook images to be built.

**Workaround (if any)**
Is there a workaround?

**Open Data Hub Version**
0.8

**OpenShift Version**
Version #: 4.4
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): Azure

**KFDef**
```
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  annotations:
    kfctl.kubeflow.io/force-delete: 'false'
  selfLink: /apis/kfdef.apps.kubeflow.org/v1/namespaces/aa-gpu/kfdefs/opendatahub
  resourceVersion: '5183062'
  name: opendatahub
  uid: 9d3309e5-1708-4d73-b1d1-1633e5000a40
  creationTimestamp: '2020-11-04T19:15:22Z'
  generation: 1
  namespace: aa-gpu
  finalizers:
    - kfdef-finalizer.kfdef.apps.kubeflow.org
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: odh-common
      name: odh-common
    - kustomizeConfig:
        parameters:
          - name: s3_endpoint_url
            value: s3.odh.com
        repoRef:
          name: manifests
          path: jupyterhub/jupyterhub
      name: jupyterhub
    - kustomizeConfig:
        overlays:
          - cuda
          - additional
        parameters:
          - name: cuda_version
            value: '10.2'
        repoRef:
          name: manifests
          path: jupyterhub/notebook-images
      name: notebook-images
  repos:
    - name: kf-manifests
      uri: >-
        https://github.com/opendatahub-io/manifests/tarball/v1.0-branch-openshift
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v0.8.0'
  version: v0.8.0
```

**Comment by carlmes** [comment]
Appears to be related to https://github.com/opendatahub-io/odh-manifests/issues/167#issuecomment-717172452

**Comment by carlmes** [comment]
And a possible workaround - changing the manifest version from `'https://github.com/opendatahub-io/odh-manifests/tarball/v0.8.0'` to `uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/master'` seems to allow the build to succeed.

Is this bug the result of a patch to master that was not retrofitted to the 0.8.0 branch perhaps?

**Comment by harshad16** [comment]
@carlmes , I have updated my fork, so that it can be used without any issue.
please check the build, if you are facing any issue, let me know.

Also, the updated Cuda build chain in the master should work well as well.

**Comment by vpavlin** [comment]
@carlmes Correct, we are working on 0.9.0 release (should be out by the end of the week) which will have this fix, so we did not backport to 0.8.0. Is that ok for you?

**Comment by carlmes** [comment]
OK great, we should be ready to perform an installation at the customer by then, so we will use the latest 0.9 release when it's generally available.

**Comment by nakfour** [comment]
@carlmes ODH 0.9 has been released, please try it out.
