### ISSUE TITLE
SPIKE: How to handle cluster-wide dependencies of ODH

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/odh-manifests#235]
**Is your feature request related to a problem? Please describe.**
ODH currently deploys Strimzi (and KF is doing that for more operators) cluster-wide. This potentially prevents or complicates deploying multiple instances of ODH on one cluster.

We need to figure out how to handle such situations.

**Describe the solution you'd like**
We could

* agree to only deploy namespace bound operators
* make variants for each operator where one would be cluster bound and one namespace bound
* implement checks to only deploy the cluster wide operator if it does not exist and only delete it if there is no one using it 

**Describe alternatives you've considered**

**Additional context**

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
