### ISSUE TITLE
Document custom manifests

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-manifests#242]
The way ODH is working, it's easy to create you own custom manifests repo and refer to it from your KfDef. So you can develop/integrate your own components without forking and maintaining the whole odh-manifests repo.
This should be better documented, and maybe even create a page that could refer to "contribs" component without including them in the main ODH.

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
