### ISSUE TITLE
How to integrate Ceph based S3 storage system with the SuperSet

### ISSUE THREAD

**Issue by kkuhu302** [opendatahub-io/odh-manifests#249]
Hello,
I am working on a scenario, where we have a need to integrate rook-ceph based s3 storage system with the SuperSet. I have been able to integrate superset with a normal aws s3 based storage but I am not so sure in how to achieve the same with an S3 compatible storage.
It would be really very helpful if you could please provide your suggestions on this.
@vpavlin @LaVLaS @crobby @goern

**Comment by goern** [comment]
@durandom

**Comment by LaVLaS** [comment]
@kkuhu302 Apologies for the delay. Depending on how the rook object storage endpoint is exposed the access should be similar to AWS S3 access. You will still need the endpoint, access key and secret key. With the Rook setup, you will need to access the rook rgw gateway for the s3 endpoint via the exposed route (external access) or the internal rgw gateway service (internal only access). 

There are other possible configuration changes that may be required based on how you have deploy Rook (unsecured endpoint, s3, path style access, ...) but you'll want to confirm that you have a Rook endpoint that will be accessible to Superset first.

**Comment by kkuhu302** [comment]
@LaVLaS  I already have endpoint,accesskey and secretkey for rook-ceph based s3 compatible storage which is accessible to other component of odh i.e. jupyterhub, seldon
and I know how to integrate superset with aws s3 with athena as a connector.

Do I need to connect rook-ceph s3 in athena itself?  what would be other possible configuration changes? Is there any reference link or document regarding this which I could refer?

**Comment by durandom** [comment]
I think it's best to refer to the SuperSet configuration. The ODH version typically connects to a thrift server, which is not yet part of the latest version of ODH.
Superset works best with SQL like backends. So you'd want to have some DB like interface that uses Rook as storage.

**Comment by kkuhu302** [comment]
@durandom  Up until now I had a understanding that rook ceph is the global storage solution of odh and accordingly had integrated it with all the components of ODH on which I was working. Can you please advice, is my understanding is correct or not, if not then is there any global storage solution for all component of odh?

As the thrift server is not present in the latest version i.e. 0.9,can you suggest any alternate for thrift server in this version.

 I have also tried with the 0.5 version of odh. But there also it is connecting with the superset but not recognising rook-ceph s3. As per the github merge request(https://gitlab.com/opendatahub/opendatahub-operator/-/merge_requests/53), Support for Rook Ceph S3 instances is not yet enabled in that version of data catalog. So, is it not possible to integrate data catalog to rook ceph based s3 in 0.5 or I am interperting it wrong.

**Comment by durandom** [comment]
@kkuhu302 not sure what you're trying to accomplish. For a simple SuperSet demo, you could install postgresql via an operator. Have a look at the SuperSet documentation.

**Comment by kkuhu302** [comment]
The dataset required to train model on jupyterhub notebooks and the trained model predictions are also saved on rook ceph based s3 storage bucket. To analyse and visualize those dataset, I am using superset and for that I need to integrate this to  my rook-ceph storage based s3 bucket. Which I don't think could be accomplised by using postgres as data connector with superset because postgres would create its own storage space on ceph, but can't use already created object bucket claim(s3 compatible storage).

**Comment by durandom** [comment]
That's not possible with stock ODH at the moment. 
You can try to replicate what we have at https://github.com/operate-first/apps - this includes a version of the DataCatalog.
You can either deploy it yourself https://www.operate-first.cloud/operators/continuous-deployment/docs/downstream/odh-install-crc.md
Or work with us to get your example into our deployment
