### ISSUE TITLE
Airflow deployment with Kubernetes executor missing "ALL" the pod level permissions in the role and hence, unable to run any schedules

### ISSUE THREAD

**Issue by pthacker22** [opendatahub-io/odh-manifests#251]
**Describe the bug**
Airflow deployment with Kubernetes executor gives below error in the scheduler pod's log post deployment --

HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \\"system:serviceaccount:puja:airflow-cluster-scheduler\\" cannot watch resource \\"pods\\" in API group \\"\\" in the namespace \\"puja\\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}\n'

Upon research, it was found that the role binded to the service account is missing all the pod level permissions like "create/watch/list/delete, etc". Check this link for role details --> https://github.com/opendatahub-io/odh-manifests/blob/master/airflow/cluster/rbac/role.yaml. This is why, the service account is not able to perform any operation on the pods. Kubernetes executor needs additional pod level privileges than the Celery executor as Kubernetes executor spins up, watches and shuts down pods during runtime.

**Steps To Reproduce**
1. Install Open data hub community edition
2. Create an ODH instance which includes Airflow operator for base and cluster
3. Create Airflow base and cluster instance following this document.. https://github.com/opendatahub-io/odh-manifests/tree/master/airflow. 
Change executor type to "Kubernetes" in the cluster deployment yaml.
4. Go to Workloads --> Pods. Click on Airflow Scheduler pod, go to log and see below error.
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \\"system:serviceaccount:puja:airflow-cluster-scheduler\\" cannot watch resource \\"pods\\" in API group \\"\\" in the namespace \\"puja\\"","reason":"Forbidden","details":{"kind":"pods"},"code":403}\n'
5. Goto Airflow UI from Routes and run any DAG, it will never complete as Airflow will not be able to spin up new pods to run the schedule

**Expected behavior**
Airflow being able to deploy new pods for the schedules to run and shutdown the pod post schedule run is complete.

**Workaround (if any)**
We binded "admin" role to the Airflow scheduler service account "airflow-cluster-scheduler" which resolved the issue.. Not an ideal workaround at all

**Open Data Hub Version**
---------------------------------------------------------
ODH version - Community Edition 0.9.0
---------------------------------------------------------
apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: opendatahub
  namespace: puja-odh
spec:
  applications:
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: airflow/operator
      name: airflow-operator
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: airflow/cluster
      name: airflow-cluster
  repos:
    - name: kf-manifests
      uri: 'https://github.com/opendatahub-io/manifests/tarball/master'
    - name: manifests
      uri: 'https://github.com/opendatahub-io/odh-manifests/tarball/v0.9.0'
  version: v0.9-branch-openshift

**OpenShift Version**
Version #: 4.5.19
Provider Openshift Dedicated on AWS

**Comment by vpavlin** [comment]
@noseka1 Can you help us with this?

**Comment by vpavlin** [comment]
Reading this again more carefully I have realized this speaks about *Kubernetes executor* which we do not support at the moment in ODH - the only one tested was Celery executor.

I believe @noseka1 has made changes to enable Kubernetes executor, so once he is back from PTO we'll get his changes in.

@pthacker22 Would you like to test the changes when they are ready to help us review it?

**Comment by pthacker22** [comment]
Thanks Vaclav. Yes, i can review, deploy and test the changes.

**Comment by pthacker22** [comment]
Hi Vaclav, Do we have any update on this?

**Comment by noseka1** [comment]
Hi @pthacker22, I just pushed the latest development version of the Airflow operator. If you are interested, this version comes with several changes which you can test:

1. Airflow was updated to version 1.10.12
2. Added support for Kubernetes Executor
3. Added support for user authentication using OpenShift OAuth or against the database, see also: https://github.com/opendatahub-io/airflow-on-k8s-operator/commit/3c4a27dc2be2f984c50b257a9c7a05ca318d75c7 for instructions on how to enable it.

We are still in the middle of testing and merging. You will need to build your docker-airflow image using this branch https://github.com/opendatahub-io/docker-airflow/pull/10 and you will need to build and deploy the Airflow operator using this branch: https://github.com/opendatahub-io/airflow-on-k8s-operator/tree/openshift-3.

**Comment by vpavlin** [comment]
I created a new issue for the Airflow update, so I'll close this one.
