### ISSUE TITLE
Option to specify storage class for superset

### ISSUE THREAD

**Issue by HumairAK** [opendatahub-io/odh-manifests#252]
**Describe the solution you'd like**
It would be nice to have an option to specify a storage class for the superset pvc like you can do for jupyterhub via a parameter as describe [here](https://github.com/opendatahub-io/odh-manifests/blob/9c91f8f38317f3d236204c842b9d3030dce9319e/jupyterhub/README.md#examples). 

**Describe alternatives you've considered**
Right now we're overriding the superset pvc [here](https://github.com/opendatahub-io/odh-manifests/blob/9c91f8f38317f3d236204c842b9d3030dce9319e/superset/base/pvc.yaml) to have the storage class annotation. It would be easier if we didn't need to do this and could just specify it as a parameter.

**Comment by nakfour** [comment]
@HumairAK this is a good feature, we want to design a way for user to specify a global storage class for all components. We will keep this feature request open for later releases

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
