### ISSUE TITLE
Amend 0.9 release notes for Grafana

### ISSUE THREAD

**Issue by guimou** [opendatahub-io/odh-manifests#253]
In the 0.9 release notes we don't mention the upgrade of the Grafana operator to 3.6.0.
This upgrade has some consequences because the Grafana version now deployed is 7.x, meaning some panels have been renamed, plus other modifications (useful ones!).
So maybe worth adding it to the notes.

**Comment by nakfour** [comment]
@guimou we list the component version which is 7.x for Grafana and not the operator version. We will list both in the next release

**Comment by guimou** [comment]
OK, but the Grafana component was not listed either. It was this one that I pointed out more than the operator version. Release notes only say:
```
2911878 Open Data Hub Dashboard v0.9
58b9489 Elyra v0.0.5
f206c0d Ceph Nano v0.7
```

**Comment by LaVLaS** [comment]
Done!
