### ISSUE TITLE
Kubeflow from ODH 0.9 does not install in namespace NOT Kubeflow

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/odh-manifests#258]
**Describe the bug**
Changing the namespace field in the KF kfdef to anything other that kubeflow will give this error below
```
WARN[0015] Encountered error applying application openshift-scc:  (kubeflow.error): Code 500 with message: Apply.Run : error when creating "/tmp/kout072658223": namespaces "kubeflow" not found  filename="kustomize/kustomize.go:266"
WARN[0015] Will retry in 8 seconds.                      filename="kustomize/kustomize.go:267"
```

**Steps To Reproduce**

**Expected behavior**

**Workaround (if any)**
Any manual steps that allow you to resolve the issue

**Open Data Hub Version**
Please attach relevant kfdef manifest if applicable

**OpenShift Version**
Version #: 
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...):

**Additional context**

**Comment by goern** [comment]
@harshad16 @pacospace @tumido Is this something that we can contribute back to ODH from https://github.com/operate-first/support/issues/62 ? and wasn't @4n4nd working on it too?

**Comment by goern** [comment]
is this still relevant with https://github.com/opendatahub-io/odh-manifests/tree/v1.0.4 ?
