### ISSUE TITLE
Getting error "One node has volume node affinity conflict" on spawning Notebook Image with GPU_COUNT=1

### ISSUE THREAD

**Issue by altruistcoder** [opendatahub-io/odh-manifests#259]
Hey,

I have used some g4dn.4xlarge nodes in my cluster having one GPU present on each node. I have been able to successfully deploy the Nvidia GPU Operator and everything seems to work fine.
But, when I am trying to spawn a notebook  image keeping the GPU_COUNT as "1", I am getting an error stating that "One node has volume node affinity conflict". When, trying to debug this issue I found that the **availability zone** where the PVC was created for the user and the **availability zone** in which the GPU node (both within the same region) was running were different, and that was causing this issue. While trying to find a solution for this, when I created another node within the same availability zone where the pvc was residing, this issue got solved.

**First** of all, I wanted to know whether this is the right solution to this problem, or there can be a better way to deal with this issue. 
**Second**, if yes, then how can I restrict ODH to make all the user PVCs into a particular availability zone only as where the GPU node is also present.

Example of some scenarios where this issue can create some problems:

1. If we have multiple GPU nodes present in one AZ and the user PVCs get created in other AZs, the GPU resources would not be utilized and we are going to see these errors very often.

2. If we have multiple GPU nodes spread across (for instance) multiple AZs to resolve this issue, and if all the PVCs (which may be a part of one or more instances of ODH) are formed in one particular AZ, then also the GPU resources formed in other AZs would not be utilized.

3. If we have multiple GPU nodes spread across (for instance) multiple AZs to resolve this issue, and a large no. of PVCs (which may be a part of one or more instances of ODH) are formed in one particular AZ more often then other AZs, then in that particular AZ, it might happen that all the GPU resources are consumed and more requests for accessing GPUs leads to "Insufficient resources" error. Also, the free GPUs present in other AZs in this case would not be utilized to their fullest.

 So, can you please provide a way on how can we **restrict ODH to make all PVCs in a particular AZ** only so that we make all the GPUs nodes in that AZ and we do not get this "Volume node affinity error" anymore.

@nakfour @LaVLaS @vpavlin @crobby

**Comment by vpavlin** [comment]
Hi @altruistcoder, this is definitely an interesting issue which we have not come across yet since, I believe, we have never tried a deployment across multiple AZs.

For that, please excuse my lack of knowledge of how OpenShift AZs to affinity - would it be possible for you to share more info?

* failing pod manifest
* PVC manifest
* PV manifest

for the broken setup described above?

I believe the nodeAffinity is set on PV by OpenShift, so that is not something we can controll, I think - maybe a specific StorageClass could help?

NodeAffinity can be set for Jupyter pods though via singleuser-profiles configMap - https://github.com/opendatahub-io/jupyterhub-singleuser-profiles#configuration

**Comment by altruistcoder** [comment]
@vpavlin 

Thanks for providing a quick response on this issue.  
I have an update on this issue. Yesterday, I turned down my openshift cluster for a couple of hours. But, when I restarted the cluster, I started seeing this same issue in the cases where no GPUs were requested as well ,i.e., the cases where the requests were only for CPUs and memory by the notebook pods.

**My PVC and the PV were already created (even before the cluster was made down) by my previous spawns of the notebook image.** 
The required manifests are as below:

PVC yaml: 
[jupyterhub-nb-username-pvc.txt](https://github.com/opendatahub-io/odh-manifests/files/5657280/jupyterhub-nb-username-pvc.txt)

PV yaml: 
[jupyterhub-nb-username-pv.txt](https://github.com/opendatahub-io/odh-manifests/files/5657282/jupyterhub-nb-username-pv.txt)

Pod yaml: 
[jupyterhub-nb-username.txt](https://github.com/opendatahub-io/odh-manifests/files/5657284/jupyterhub-nb-username.txt)


When I spawned the notebook image after bringing up the cluster again, the error which I am seeing on spawning the pod:

![Node-Affinity-Error](https://user-images.githubusercontent.com/31319270/101448514-291d8e80-394d-11eb-955d-de0dd9f7caab.png)

**Comment by vpavlin** [comment]
Ok, so this seems like OpenShift was actually not able to find a node to schedule this pod on. If you look at the error again, it says:

* 1 node has volue conflict - i.e. cannot mount that PV(C)
* 2 nodes have insufficient memory
* 4 nodes have insufficient cpu

That gives us all the 7 nodes - that 1 node with affinity issue is definitely weird, but the rest just means the pod is too big for the nodes in the cluster - it should go away if you select smaller size.

**Comment by altruistcoder** [comment]
Yes, you are definitely correct on that point. If I decrease the size then I might be able to spawn my notebook image successfully in this case but there can be other cases as well where we might get stuck due to this "volume node affinity conflict" error.

Please pardon me for a long writeup, I might explain this better with a **scenario**. Suppose, I have 3 worker nodes in our cluster (say aws ec2 m5.4xlarge machines), one each in the three AZs viz, "us-east-2a", "us-east-2b", "us-east-2c".
Now, suppose a user comes and spawns a notebook image and the user **pod gets placed on the node in "us-east-2a" AZ**. Then, user's PV would be created in the "us-east-2a" AZ and if we inspect the definition file of the created PV, we will see something like this present in it:
```
nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: failure-domain.beta.kubernetes.io/zone
              operator: In
              values:
                - us-east-2a
            - key: failure-domain.beta.kubernetes.io/region
              operator: In
              values:
                - us-east-2
```
Now, suppose user stops his notebook server temporarily and spawns a particular notebook image again after some time. Meanwhile, the node present in the "us-east-2a" AZ is consumed with resources so that it is not able to fulfill the demand of resources requested by the user, then in that case the user's pod would be placed in either "us-east-2b" or "us-east-2c" AZ. As soon as this happens we will see this `volume node affinity conflict" error as the user's PV and the Pod would now in different availability zones in this case.
So, in such cases users might get some trouble working on this.

**Comment by vpavlin** [comment]
I think this is a very valid case and actual issue that needs to be addressed, but it is not something we can fix in Open Data Hub - this seems like an issue that needs to be raised with the OpenShift team.

**Comment by mmgaggle** [comment]
If `volumeBindingMode: WaitForFirstConsumer` is used on a on PVC, then the PVC will be created with knowledge of the constraints of where the pod is scheduled (ie. created in particular zone). A nodeSelector can steer a pod to a particular AZ (so a WaitForFirstConsumer PVC is scheduled there), and if used on a deployment, any replacement pods (due to failure, scale down, etc) will only be scheduled to nodes in that zone, where the PV exists.

This is problematic if there exist other constraints (hosts full, no GPUs) in the zone where the PVC was created.  There are CSI provisioners that can provide "regional" persistent volumes, that can be attached from any availability zone. We do this by default with Red Hat's OpenShift Container Storage product, but such a configuration is also achievable with upstream Rook/Ceph and a number of other solutions.

**Comment by altruistcoder** [comment]
Thanks a lot @mmgaggle & @vpavlin for suggesting steps to resolve this issue. I used rook-ceph's storage class (having CSI provisioner) instead of the default "gp2" and I was able to resolve this volume node affinity conflict error. 

I have more query. Due to limitations of resources I want to give users the option to choose **only one GPU at max.** for now. I know for this I would have to make some changes in the **Spawner Form in UI**. I was able to find this source code [repo](https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/tree/master/jupyterhub_singleuser_profiles/ui) of the UI but I am not able to find where exactly I can find this code in JupyterHub Pod and make the suitable changes so as to remove the option for entering the GPU_COUNT in the spawner form. 
So, can you please help in finding the location where exactly I can make these changes.

**Comment by altruistcoder** [comment]
Hey,

I tried going through different files and folders of the Jupyterhub pod as well but I was not able to find the relevant piece of code where I should make changes to customize the JupyterHub UI. 
Can you please help me locate the piece of code I need to change?

**Comment by vpavlin** [comment]
@altruistcoder I created an issue on the library you found for this and @mroman-redhat should be able to take a look in the future.

I'll close this issue now, feel free to reopen if you have more questions regarding the original issue
