### ISSUE TITLE
Use ODH Operator to manage multiple namespaces

### ISSUE THREAD

**Issue by anishasthana** [opendatahub-io/odh-manifests#26]
We are currently using the ODH operator 0.5 to deploy operators in a "per-namespace" manner.

1. dh-analytics-factory: Data Catalog, Spark (This spark operator is used to support the data catalog as well as user workloads)
2. dh-argo: Argo Workflows
3. dh-superset: Superset
4. dh-data-catalog-a: Data Catalog, Spark (This spark operator is used to support the data catalog)
5. dh-data-catalog-b: Data Catalog, Spark (This spark operator is used to support the data catalog)
6. dh-jupyterhub: Jupyterhub, Spark

We are currently doing this by having one instance of the ODH operator per namespace as well as a different CR we are using for every namespace. What is the recommended approach with the upcoming 0.6 release of the operator?

**Comment by nakfour** [comment]
With ODH 0.6 we have a cluster wide operator, and you can create instances of different `kfdef` in different namespaces.
