### ISSUE TITLE
Unable to install dependencies using yum in jupyterhub

### ISSUE THREAD

**Issue by kkuhu302** [opendatahub-io/odh-manifests#274]
Hello,
I was trying to install certain python libraries  in s2i-minimal-notebook on jupyterhub. For that I needed to run yum install command in the terminal. But I was not able to run it because I don't have root access on that pod. 
So, is there any way round to use yum inside jupyter-notebook?
Because there are many dependencies which could not be install through pip and being inside container I would not get root access.
@vpavlin @LaVLaS

**Comment by vpavlin** [comment]
Hi @kkuhu302, this is expected - OpenShift does not allow us to run pods as root unless we remove some security features.

If you need to use yum/dnf to install some non-Python dependencies, you will need to build your own Jupyter Notebook image.

You can follow a similar approach we took for Spark Notebook images:

1. build your own base - e.g. https://github.com/opendatahub-io/s2i-spark-container/blob/master/python-3.6/Dockerfile
2. Use base for your own `s2i-minimal-notebook` image, which you can find here: https://github.com/thoth-station/s2i-minimal-notebook

You can build 1. in Quay.io and then use a BuildConfig like this https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/build/minimal-notebook-buildconfig.yaml to produce the 2.

Let me know if you have more questions

**Comment by kkuhu302** [comment]
@vpavlin 
Thanks for your quick response. This approach is logical and we are doing somewhat same for adding non-python dependencies. 
But in my scenario we have a very large team which is using odh and each one of us is requiring different sets of libraries in which many of them have non-python dependencies. So to build a new image everytime for each person is not feasible and thats why we were trying to find out a workaround. It would be very helpful if you could help us in this regard.

**Comment by vpavlin** [comment]
I understand your concerns, but I am afraid there is no easy and sane workaround.

If you want to go crazy, you can make the Jupyter pods privileged, hence yum would work, but I would strongly discourage this approach.

You could potentially provide a somewhat automated service for users where they'd submit list of packages they need and you'd generate Dockerfiles and build it. Obviously this is not something we can help with or provide at the moment. CCing @goern, I am not sure, but maybe there is something in Thoth project that could help with this?

We also had a feature request (https://github.com/opendatahub-io/odh-manifests/issues/248) to provide ability to pull images from multiple namespaces, if we build this into ODH JH, users could build their own images in their namespaces and an admin would just whitelist the namespace in JH, so users would be in control of what they get. But we have no timeline for implementing this feature - if you are interested in contributing, I could provide guidance:)

**Comment by kkuhu302** [comment]
I was creating image to include gdal library i.e Geospatial Data Abstraction Library. It needs gdal-config, to be installed. For that I have installed gdal-devel through rpm packages. But the version it contains i.e. 1.11.4 is not supported by pypi version of gdal. The rpm package for gdal-devel for centos is only for 1.11.4 version. Is there any way to install gdal on rhel?

**Comment by vpavlin** [comment]
TBH I have no idea about availability of that lib on RHEL. One thing you could do is to build your notebook image on top of CentOS or Fedora where you should be able to install such libraries.

You would basically want to use the `build` overlay for `notebook-images` component and replace the base images for minimal-notebook - https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/build/minimal-notebook-buildconfig.yaml#L21
