### ISSUE TITLE
Update Airflow to 1.10.12 to enable k8s executor

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/odh-manifests#276]
**Is your feature request related to a problem? Please describe.**
We'd like to update Airflow to 1.10.12

Quoting @noseka1 from issue #251 

> Hi @pthacker22, I just pushed the latest development version of the Airflow operator. If you are interested, this version comes with several changes which you can test:

> Airflow was updated to version 1.10.12
> Added support for Kubernetes Executor
> Added support for user authentication using OpenShift OAuth or against the database, see also: opendatahub-io/airflow-on-k8s-operator@3c4a27d for instructions on how to enable it.
> We are still in the middle of testing and merging. You will need to build your docker-airflow image using this branch opendatahub-io/docker-airflow#10 and you will need to build and deploy the Airflow operator using this branch: https://github.com/opendatahub-io/airflow-on-k8s-operator/tree/openshift-3.

**Comment by reetika-vyas** [comment]
Hi @vpavlin ,
@noseka1  added the pod's permissions here https://github.com/opendatahub-io/airflow-on-k8s-operator/blob/openshift-3/config/rbac/role.yaml. Can you please merge these changes to  master branch?
