### ISSUE TITLE
Pod accessing GPU even when GPU_COUNT set to '0'

### ISSUE THREAD

**Issue by kkuhu302** [opendatahub-io/odh-manifests#279]
Hello @vpavlin,

In my case, I am using a cluster which consists of all worker nodes having GPU in them. When I write `nvidia-smi` command in terminal, the environment is able to recognize the GPU even when I have not selected GPU_COUNT as 1 during the spawning
of the notebook. The notebook which I am spawning is a **Tensorflow notebook built with the cuda chain** using the build-configs present [here](https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images/overlays/cuda).
 
I am also able to see the GPU utilization > 0% in the output of the nvidia-smi command during the training of a model. When I am checking my pod definition file created after spawning the image, I am unable to see `nvidia.com/gpu: '1'` under the **resources** section as well.
According to my understanding, the system should not let my pod use GPU if I have selected GPU_COUNT as '0'.
 
So, can you please tell if this is the proper functioning of the system or I am making some mistake.

@harshad16

**Comment by vpavlin** [comment]
Hi @kkuhu302! Thanks for reaching out. This is very strange behaviour.

The way `GPU_COUNT=1` work is that it simply translates to `nvidia.com/gpu: '1'` when the pod manifest is produced. ODH does not influence how GPUs are propagated into the pods other then adding that resource request.

I do not have access to cluster with GPUs at the moment to verify this happening - @LaVLaS any thoughts on this? Who could we pull in from OpenShift to help @kkuhu302 debug?

**Comment by kkuhu302** [comment]
I also tried putting a default limit and request as `nvidia.com/gpu: '0'` with the use of **limit-ranges**, along with keeping **GPU_COUNT as '0'** while creating the pod. These were reflected in the pod definition file after I spawned the notebook image but still the pod was able to use GPU for training the ML models.
 
To get more clarity of the situation, I tried running a pod having CUDA and GPU support installed with Tensorflow and `nvidia.com/gpu` set as '0', but still that pod was also able to utilize the GPU for training the model.

I am also thinking to create _s2i-minimal_ and _Tensorflow_ images **without having the CUDA support** to avoid the image using GPU when we do not want it to. I am not sure if it would work but if it works, it might be a temporary solution to this problem.
I would be happy if you could provide your suggestions/inputs on this idea @vpavlin

**Comment by vpavlin** [comment]
I am not sure about what you mean by Tensorflow images without CUDA support - we have those - https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images/overlays/additional

Can you elaborate?

**Comment by kkuhu302** [comment]
Yes, exactly. I meant to refer to these images only. I saw that in case of these images, the environment doesn't access the GPU when the GPU_COUNT has been set as '0'.
So, can using the non-cuda based images when we do not want to access GPU and using the cuda-build-chain based images when we want to run our notebook images on GPU, be a temporary solution for this problem right now? 
 
I considered this as a temporary solution because even if we do this, the notebook images having CUDA in them would still be able to access the GPUs  when we do not intend them to, so our main problem would still persist in this case as well, but there would be a workaround to restrict users from unintentionally using GPUs by choosing a different image (non-cuda based one)
WDYT?

**Comment by vpavlin** [comment]
Well, that is definitely an option - although we do not have an option to "restrict" which images are visible to which users, so it would still be up to the users to select the right image (GPU enabled or not).

I still believe that this is a bug in OpenShift unless your OCP is somehow "broken" for other reasons, so it would be best to find someone with more knowledge of the GPU topic to help debug and find the real problem

**Comment by vpavlin** [comment]
@sjug Hey, @kkuhu302 reported that *all* his pods on a GPU enabled node in the cluster have access to the GPU regardless whether the `nvidia/gpu` resource request is set. Have you seen this before?

**Comment by dfeddema** [comment]
This is the expected behavior.  Although, I think we could improve the documentation on this. 
https://github.com/NVIDIA/k8s-device-plugin
WARNING: if you don't request GPUs when using the device plugin with NVIDIA images all the GPUs on the machine will be exposed inside your container.

**Comment by vpavlin** [comment]
@kkuhu302 Diane submitted a BZ report here: https://bugzilla.redhat.com/show_bug.cgi?id=1918530

**Comment by kkuhu302** [comment]
Hello @vpavlin,
 
According to Diane, it is an expected behavior of the pods being able to access GPUs, if they are scheduled on GPU nodes by the Openshift scheduler (which might be due to resource constraints on CPU nodes or due to the cluster having all GPU nodes) even when the GPU_COUNT has been set to 0. But, can't we do anything for it and should it be considered as a normal behavior of the system?    
  
I also went through the BZ report you shared and tried to follow the suggested steps of specifying `privileged: false` under the "securityContext" of the user pod, but that also didn't worked and I was still able to access the GPUs while GPU_COUNT was set to 0.

One workaround that comes to my mind is having both GPU as well as non-GPU nodes in our cluster. So in that case, the jupyter notebook pods with GPU request are always going to be placed on GPU nodes. But, is there any way to restrict the notebooks (which do not request GPU) only to non-GPU nodes.

**Comment by vpavlin** [comment]
AFAIK after talking to Diane there is no other way than adding non-GPU nodes to the cluster - so I would not consider this a workaround, but a solution:)

Sadly, we cannot do much with this from ODH

**Comment by kkuhu302** [comment]
Hello @vpavlin,  
I agree that it can be a solution for this problem but there can be cases where we might face issues with this as well. For instance, if the scheduler, for some reason, places the pod on GPU nodes even when the cluster has non-GPU nodes (like if the non-GPU nodes do not meet the requirements for CPUs or memory) then the pod placed on the GPU node will have the same condition as now.
Can we avoid this condition anyway or is it a permanent issue?

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
