### ISSUE TITLE
Not able to enable GPU in openshift cluster

### ISSUE THREAD

**Issue by kkuhu302** [opendatahub-io/odh-manifests#281]
For accessing nvidia GPU from Jupyterhub Notebooks, I have deployed node feature discovery operator and NVIDIA GPU operator.
I have achieved this by following links present in the [document](https://opendatahub.io/docs/administration/advanced-installation/gpu.html). But the gpu-feature-discovery pod created by gpu operator is giving error: `Failed to download metadata for repo 'rhel-8-for-x86_64-appstream-rpms': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried`. Can you please advice where am I going wrong in following the document mentioned above.

**Comment by LaVLaS** [comment]
@kkuhu302 On which step of the gpu operator install instructions did you experience this issue?

[Enabling Nvidia GPU support in OpenShift](https://docs.nvidia.com/datacenter/kubernetes/openshift-on-gpu-install-guide/#openshift-gpu-support)

**Comment by LaVLaS** [comment]
@kkuhu302 Is this still an issue?

**Comment by kkuhu302** [comment]
Hello,  
Sorry for late reply. This issue has been solved.
 After 2 days of the error, I just delete all instances of GPU operator and installed again. That time it get installed correctly.
