### ISSUE TITLE
Add Jupyterhub Singleuser Profiles documentation to opendatahub.io

### ISSUE THREAD

**Issue by mroman-redhat** [opendatahub-io/odh-manifests#288]
It might be helpful to users if we had JupyterHub section in the opendatahub.io documentation page. where the capabilities of the JupyterHub Singleuser Profiles library would be shown.

It was decided that the best approach would be to show some basic use cases and create tutorials for them and then link the repo documentation to them for more information.

For example we could describe a situation where the admin needs to define specific sizes for the jupyter notebooks that the user can choose from, and then there would be a short tutorial showing (with images) which configmap to modify and an example yaml with the sizes changed.

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.

**Comment by mroman-redhat** [comment]
MIgrated to: https://issues.redhat.com/browse/ODH-401
