### ISSUE TITLE
Not able to create virtual environments using built-in Python "venv" module on jupyter notebooks

### ISSUE THREAD

**Issue by altruistcoder** [opendatahub-io/odh-manifests#294]
Hello,

I am working on a use case for which I needed to create different python virtual environments so as to use different sets of python dependencies having different versions. I am able to create & use virtual environments using the `virtualenv` package after installing it through **pip**, but I am not able to do it using the built-in `venv` module which is provided & preferred by Python officially for creating virtual environments.
I see the following error when I try to run the respective command as shown below:

![image](https://user-images.githubusercontent.com/31319270/106024411-c7c4a100-60ed-11eb-85ff-033f7fa70c57.png)

I tried to do the same on an *Ubuntu* VM but it required me to install *python3-venv* package first and then I was able to successfully create a virtual environment using the command shown in the image above.
I also created two VMs for *RHEL-7* and *RHEL-8* respectively, and I was able to create virtual environments in them as well after installing python in them using yum.

Can you please assist me in resolving this issue with the **venv** module happening on the jupyter notebook images?

**Comment by vpavlin** [comment]
Assuming you did this in Jupyter Terminal. I tried to reproduce this, but it worked fine:

```
[1000660000@jupyterhub-nb-vpavlin ~]$ python -m venv xyz
[1000660000@jupyterhub-nb-vpavlin ~]$ 
```

Any other pointers for me to reproduce this?

**Comment by altruistcoder** [comment]
Hello @vpavlin,

I agree that this command is not giving the above specified error when we try to run it on the default imagestreams that come with ODH. 
But, in this case also, I expect that there should be no dependencies pre-installed in this new virtual environment (for instance, *"xyz"* in this case) created using the above command, but that is not happening. When I run `pip freeze` after activating this virtual environment, I am able to see exactly the same list of dependencies which are installed in the home environment (outside of virtual environment) by default.

**Comment by vpavlin** [comment]
Ok, interesting. It was not clear that the issue actually is that you see all the packages installed in the main virtual env when you switch to the new virual env. I am not sure why/how this works - maybe it is because of the way how these s2i images are constructed.

@harshad16 @fridex any thoughts?

**Comment by altruistcoder** [comment]
@vpavlin Actually, both of the issues are there depending on the image in which virtual environment is being created.

Out of the images that come by default with ODH, in the `s2i-spark-minimal-notebook:py36-spark2.4.5-hadoop2.7.3` & `s2i-spark-scipy-notebook:3.6` images, I am seeing the error of which I have shared the screenshot above. In the other default ODH images, the other scenario is occurring where the new virtual environments come non-empty (i.e. showing same list of dependencies as home env).

I have some other images as well that are created using the cuda-build-chains provided [here](https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images/overlays/cuda) with the only difference being that they spawn in the form of Jupyter Labs instead of the standard Jupyter notebooks (For enabling Jupyter Lab as the default view in ODH, I follow the process @harshad16 suggested me [here](https://github.com/opendatahub-io/odh-manifests/issues/167#issuecomment-726771004)). In these images as well, I am seeing the same error as in the screenshot shared above.

**Comment by altruistcoder** [comment]
@vpavlin @harshad16 can you please help me out in resolving this error?
