### ISSUE TITLE
Add README for AI Library

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/odh-manifests#30]

**Comment by adrian555** [comment]
@vpavlin is there a first version of how to use AI library operator in the ODH? I don't need it to be fully ready but would like to have one example to try this out on our ODH deployment. Thanks.

cc @animeshsingh

**Comment by vpavlin** [comment]
Hi @adrian555, ai-library depends on Seldon and we were not able to get that in in time for 0.6.0. We are planning it for 0.6.1 - see https://github.com/opendatahub-io/odh-manifests/issues/45

If you want to try ai-library anyway, maybe @crobby can provide few pointers
