### ISSUE TITLE
Upgrade from v0.9 to v1.0.0: Superset DeploymentConfig rollout blocked by PVC

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/odh-manifests#308]
**Describe the bug**
Superset's `DeploymentConfig` is supposed to rollout a new pods. At the same time the Superset init job is expected to prepare the database on PVC. This PVC is `readWriteOnce`, so the deployment is blocked

**Steps To Reproduce**
1. Have a `v0.9` deployment available
2. Update the repository to `v1.0.0`
3. This applies https://github.com/opendatahub-io/odh-manifests/pull/212 PR
4. The deployment is unable to complete

![image](https://user-images.githubusercontent.com/7453394/107521254-9c908600-6bb2-11eb-9200-838598415d97.png)

**Expected behavior**
Smooth rollout

**Workaround (if any)**
Delete/kill the previous pods. 

**Open Data Hub Version**
Migrating from `v0.9` to `v1.0.0`

**OpenShift Version**
Version #: 4.5
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): OpenStack

**Additional context**
https://github.com/operate-first/apps/issues/231#issuecomment-776733590

**Comment by nakfour** [comment]
We will change the Deployment config for superset to use re-create policy and not rolling update.

**Comment by nakfour** [comment]
@tumido please review https://github.com/opendatahub-io/odh-manifests/pull/317

**Comment by tumido** [comment]
Changes applied as part of our z-stream upgrade. Verified. :+1: Thank you and sorry for a late response on this.
