### ISSUE TITLE
Upgrade from v0.9 to v1.0.0: A service monitor should be deleted by the operator leaves it in place 

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/odh-manifests#309]
**Describe the bug**
ServiceMonitor should be deleted

**Steps To Reproduce**
1. Have a `v0.9` deployment available
2. Update the repository to `v1.0.0`
3. This applies https://github.com/opendatahub-io/odh-manifests/pull/271 PR
4. The service monitor `jupyterhub-metrics` should be deleted but it remains in the cluster

**Expected behavior**
The service monitor `jupyterhub-metrics` should be deleted

**Workaround (if any)**
Delete it manually

**Open Data Hub Version**
Migrating from `v0.9` to `v1.0.0`

**OpenShift Version**
Version #: 4.5
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): OpenStack

**Additional context**
https://github.com/operate-first/apps/issues/231#issuecomment-776753365

**Comment by nakfour** [comment]
@tumido we added a new feature request https://github.com/opendatahub-io/opendatahub-operator/issues/95
