### ISSUE TITLE
[JH] update to new JH version breaks metrics scraping

### ISSUE THREAD

**Issue by 4n4nd** [opendatahub-io/odh-manifests#314]
After the recent jupyterhub update, the `/metrics` enpoint is protected behind the auth proxy by default. We need to manually change the configuration to make `/metrics` endpoint scrapable.

We made this change in the MOC operate-first environment (PR: https://github.com/operate-first/apps/pull/255)

**Comment by maulikjs** [comment]
We are also tracking this on the ODH board here: https://issues.redhat.com/browse/ODH-332

**Comment by nakfour** [comment]
Fixed by #330
