### ISSUE TITLE
Implementing CICD with ODH

### ISSUE THREAD

**Issue by altruistcoder** [opendatahub-io/odh-manifests#318]
Hello,

This is not an issue but a query that I needed to ask. 

I was thinking of building my understanding on the implementation of CICD for ML workloads using the components available in ODH. I know that ODH project has been built for providing components & open source tools which are useful for performing various tasks involved in different phases of an ML lifecycle such as Seldon for model deployments, elyra for building pipelines, s3 compatible storage for storing various artifacts, etc. But I am not able to infer whether all the components required for building an end-to-end ML production CICD are present or we need to integrate more tools and how we can make use of all these tools to create a CICD for ML use cases.

In general, can you please share your idea of what all phases need to be included in & how we can create a production ready CICD for training, running, and deploying ML workloads.

**Comment by goern** [comment]
Hey Rishabh, thanks for opening this discussion. I think you are touching some areas here, and CICD might also be expressed as 'an end-to-end workflow, from Data Scientist to prediction service in production', right? One good starting point is https://github.com/thoth-station/elyra-aidevsecops-tutorial/blob/master/README.md it covers a lot of the steps.

With [Project Thoth](https://github.com/thoth-station), we aim to create a predictable and reproducible deployment of machine learning applications. From our point of view, one important feature of an ml application is metrics wrt the ml performance (like the latency of the prediction, accuracy, memory consumption, ...), these metrics could be feedback into a CD pipeline. 

Let me know if you want to share more ideas or if you want to work on specific tasks. The community is open!

@pacospace
