### ISSUE TITLE
Use Elyra 2.*/Jupyterlab3 to run KFP on Tekton in ODH

### ISSUE THREAD

**Issue by pacospace** [opendatahub-io/odh-manifests#327]
**Is your feature request related to a problem? Please describe.**
As Data Scientist,

I would like to use Elyra with KFP + Tekton in ODH.

**Describe the solution you'd like**
Have an image with Elyra 2.*/Jupyterlab3 that is compatible with KFP + Tekton.

**Describe alternatives you've considered**

**Additional context**

cc @akchinSTC

**Comment by pacospace** [comment]
It seems they recommend JH 1.3: https://discourse.jupyter.org/t/jupyterhub-docs-with-instructions-on-how-to-use-jupyterhub-with-jupyterlab-3-0/8059 @vpavlin @harshad16

**Comment by nakfour** [comment]
We built the image we just need to update it in odh manifest: https://github.com/opendatahub-io/s2i-lab-elyra/pull/16

**Comment by pacospace** [comment]
> We built the image we just need to update it in odh manifest: [opendatahub-io/s2i-lab-elyra#16](https://github.com/opendatahub-io/s2i-lab-elyra/pull/16)

👏🏼 to @harshad16 🥇 💯  we were able to test in Operate First and used it in the ML Prague workshop: https://www.operate-first.cloud/users/elyra/README.md

**Comment by harshad16** [comment]
The Release of v0.0.6 for elyra would be done end of today and a corresponding update for odh-manifest would be sent. :+1:

**Comment by goern** [comment]
What is the state of this?

**Comment by ptitzler** [comment]
The 2.0.1 image is available but we are unable to test/use it due to https://github.com/opendatahub-io/odh-manifests/issues/357 and https://github.com/opendatahub-io/odh-manifests/issues/319

**Comment by nakfour** [comment]
Elyra with KFP Tekton is available with the latest Elyra image: https://github.com/opendatahub-io/odh-manifests/pull/419
