### ISSUE TITLE
[Airflow] KubernetesPodOperator can't log or poll for status

### ISSUE THREAD

**Issue by wseaton** [opendatahub-io/odh-manifests#343]
**Describe the bug**

The `KubernetesPodOperator` can launch pods in the namespace it sits in but cannot ~poll them for progress~ retrieve their logs. This occurs by default or if `get_logs=True` in the dag.

Pod log example:

```
User \\"system:serviceaccount:edaodh-uat:default\\" cannot get resource \\"pods/log\\" in API group \\"\\" in the namespace \\"edaodh-uat\\"","reason":"Forbidden","details":{"name":"airflowtest-f754e4dd4ad64c2183a9b0086d0a5122","kind":"pods"},"code":403}\n'
```

**Open Data Hub Version**
master

**OpenShift Version**
Version #: 4.6
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): OSD

**Additional context**

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
