### ISSUE TITLE
[Query] Max load on one Instance of Jupyterhub?

### ISSUE THREAD

**Issue by altruistcoder** [opendatahub-io/odh-manifests#370]
Hello, 

This is not related to any issue which I am facing but something I am curious to know.
Is there a particular limit on the number of users that can spawn their images and have their sessions running on one instance of ODH? Can we expect some latency if the number of users are high and all are working on one instance of ODH installed in one Openshift project.
Also, is there any way to scale the number of pods running for jupyterhub so as to balance the load between them.

**Comment by vpavlin** [comment]
Hey,

There is not particular number. The most we had in one of our instances at one time was probably ~100 and we did not see any performance issues.

The main limiting factor is the size of the cluster, not the JupyterHub.

At this point it is not possible to scale JH to multiple pods for load balancing. We are working on a change which would make the proxy, which JH uses, run outside of JH pod which would allow for the load balancing.
