### ISSUE TITLE
Add a component tile to ODH Dashboard for the OpenShift Pipelines component

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-manifests#374]
**Is your feature request related to a problem? Please describe.**
When #337 is merged, the ODH Dashboard needs to display when OpenShift Pipelines is deployed by ODH

**Describe the solution you'd like**
If OpenShift Pipelines is installed by ODH, we need to a tile to the ODH dashboard to reflect that state

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by nakfour** [comment]
we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.
