### ISSUE TITLE
Using GPUs in Model Inference Servers

### ISSUE THREAD

**Issue by altruistcoder** [opendatahub-io/odh-manifests#379]
Hello,

I know that we have provision of Enabling GPUs for training models in the architecture of Open Data Hub. Also, we have Seldon for deploying the models in the form of Inference Servers which can be used to take predictions from the trained models.

Can you please tell me whether there is any way to use GPUs in the Inference Servers while providing the predictions from the trained models as very often there can be scenarios such as where the models are very heavy or the input data sent (whose predictions needs to be find) is very large in size or any other such case. In such real-time scenarios, there can be a need to provide the predictions quickly without taking much time which in turn requires a heavy processing unit such as GPUs?

**Comment by nakfour** [comment]
Hi @altruistcoder I am not sure this can all be done with Seldon. If you have GPU enabled on your OCP cluster you should be able to use it from any component that supports GPU. Here is an example working with Nvidia inference service: https://docs.seldon.io/projects/seldon-core/en/v1.1.0/examples/nvidia_mnist.html
