### ISSUE TITLE
Unable to use JupyterHub's Notebook Server API 

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/odh-manifests#391]
**Describe the bug**
User tries to access Notebook Server API from within a running JH classic notebook. `/api` endpoint is returning content as expected anything nested `/api/*` is returning `404`.

**Steps To Reproduce**
1. Go to https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/
2. Spawn `s2i-minimal-notebook` image
3. Open a new Notebook
4. Run following:

```python
>>> import requests
>>> from notebook.notebookapp import list_running_servers
>>> info = next(list_running_servers())
>>> info
{'base_url': '/user/tcoufal@redhat.com/',
 'hostname': '0.0.0.0',
 'notebook_dir': '/opt/app-root/src',
 'password': False,
 'pid': 137,
 'port': 8080,
 'secure': False,
 'sock': '',
 'token': '',
 'url': 'http://0.0.0.0:8080/user/tcoufal@redhat.com/'}
>>> r = requests.get(f'{info["url"]}api')  # http://0.0.0.0:8080/user/tcoufal@redhat.com/api
>>> r.status_code
200
>>> r.json()
{'version': '6.2.0'}
>>> r = requests.get(f'{info["url"]}api/status')  # http://0.0.0.0:8080/user/tcoufal@redhat.com/api/status or anything nested really
>>> r.status_code
404
```

**Expected behavior**
Can you please provide us guidance on how users can access the Notebook API properly?

**Workaround (if any)**
n/a

**Open Data Hub Version**
v1.0.8 in Operate First

**OpenShift Version**
Version #: 4.7.2
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): Baremetal

**Additional context**
https://github.com/operate-first/support/issues/207
https://petstore.swagger.io/?url=https://raw.githubusercontent.com/jupyter/notebook/master/notebook/services/api/api.yaml
https://github.com/jupyter/jupyter/wiki/Jupyter-Notebook-Server-API#Kernel-API

**Comment by LaVLaS** [comment]
The environment variable `JUPYTERHUB_API_TOKEN` should have the token required to authenticate api calls by passing the header `Authorization: token {JUPYTERHUB_API_TOKEN}`

```python
>>> import os
>>> import requests
>>> from notebook.notebookapp import list_running_servers
>>> info = next(list_running_servers())
>>> info
{'base_url': '/user/llasmith@redhat.com/', 'hostname': '0.0.0.0', 'notebook_dir': '/opt/app-root/src', 'password': False, 'pid': 137, 'port': 8080, 'secure': False, 'sock': '', 'token': '', 'url': 'http://0.0.0.0:8080/user/llasmith@redhat.com/'}
>>> r = requests.get(f'{info["url"]}api')
>>> r.status_code
200
>>> r.json()
{'version': '6.2.0'}
>>> r = requests.get(f'{info["url"]}api/status',
... headers={'Authorization':f"token {os.environ['JUPYTERHUB_API_TOKEN']}"})
>>> r.status_code
200
>>> r.json()
{'connections': 1, 'kernels': 1, 'last_activity': '2021-05-26T19:26:13.960456Z', 'started': '2021-05-26T18:20:05.439005Z'}
```
