### ISSUE TITLE
ODH 1.0.10 z-stream release introduced reconcile

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/odh-manifests#412]
**Describe the bug**
1.0.10 introduced a reconcile - which is a big feature, at least for us, since it introduced some fighting over resources with our ArgoCD and forcing ArgoCD into out of sync - in sync loop. 

Can this be at least mentioned in the changelog please? 
https://github.com/opendatahub-io/odh-manifests/releases/tag/v1.0.10
![image](https://user-images.githubusercontent.com/7453394/115891031-e8369a00-a455-11eb-9166-62f2f5e94722.png)

https://github.com/opendatahub-io/opendatahub-operator/releases/tag/v1.0.10 
![image](https://user-images.githubusercontent.com/7453394/115890856-b291b100-a455-11eb-887e-f3346a98b34f.png)

**Additional context**
https://github.com/operate-first/apps/pull/560

Maybe such features should rather trigger Y stream release. 

Raising this ticket to you since we think it's worth at least mentioning in the changelog, can you please add it?

**Comment by nakfour** [comment]
@tumido we will make sure our zstreams for all repos have a change log and are promoted to releases
