### ISSUE TITLE
Prometheus operator is unmaintained - consider removing this component

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/odh-manifests#417]
**Is your feature request related to a problem? Please describe.**
After discussing this with prometheus operator and Openshift Monitoring upstream - the prometheus operator via OLM is not maintained. OpenShift Monitoring suggests to use user workload monitoring instead and to use a centralized Prometheus instance in OpenShift Monitoring.

This component may be considered for removal by ODH.

Related: https://github.com/opendatahub-io/odh-manifests/pull/399
More explanation: https://github.com/operate-first/SRE/issues/272

**Comment by nakfour** [comment]
@tumido we are migrating to https://issues.redhat.com/projects/ODH/summary can you please move all your open issues there.

**Comment by tumido** [comment]
Done: https://issues.redhat.com/browse/ODH-403

**Comment by shalberd** [comment]
Yes, using monitoring for user defined projects for non-openshift* and possibly non-kube* namespaces is the way to go. 

https://docs.openshift.com/container-platform/4.9/monitoring/enabling-monitoring-for-user-defined-projects.html

https://docs.openshift.com/container-platform/4.9/monitoring/enabling-monitoring-for-user-defined-projects.html#granting-users-permission-to-monitor-user-defined-projects_enabling-monitoring-for-user-defined-projects

We ran into problems with alerts routing to the central cluster altertmanager when putting PrometheusRule in openshift* namespaces, e.g. openshift-gitops, so beware of that ("you cannot create alerting rules for the openshift-* core OpenShift Container Platform projects. OpenShift Container Platform monitoring by default provides a set of alerting rules for these projects*).

https://docs.openshift.com/container-platform/4.9/monitoring/managing-alerts.html#creating-alerting-rules-for-user-defined-projects_managing-alerts

Monitoring for user defined projects is only for user namespaces. 
Unsure about where ODH puts the running components and whether namespace starting with kube*, like kubelfow, would be a problem for proper separation of alerts (PrometheusRule objects) cluster vs. user defined projects.
