### ISSUE TITLE
Propose a better approach for credential management in ODH documentation

### ISSUE THREAD

**Issue by rimolive** [opendatahub-io/odh-manifests#420]
**Is your feature request related to a problem? Please describe.**
Currently credentials management for components in ODH (database and S3 credentials, to be more specific) varies from one component to other. There should be a documented way to do credentials management across all ODH components

**Describe the solution you'd like**
A dedicated section in the ODH documentation explaining one or more approaches to do credential management

**Describe alternatives you've considered**
In the community thread, there is a proposal to use Hashcorp Vault. But other options would be preferable as users want more options to do this.

**Additional context**
N/A

**Comment by nakfour** [comment]
Yes we are aware of this and its a great idea
