### ISSUE TITLE
Release mismatch v1.0.11 vs 1.0.11

### ISSUE THREAD

**Issue by tumido** [opendatahub-io/odh-manifests#423]
**Describe the bug**
Current z-stream release of ODH created 2 release tags with different commit `HEAD`.

https://github.com/opendatahub-io/odh-manifests/releases/tag/1.0.11
vs
https://github.com/opendatahub-io/odh-manifests/releases/tag/v1.0.11

I think we should be using `v1.0.11`, despite our upgrade pipeline triggered on the first one. Which release tag is the proper one?

Reference: https://github.com/operate-first/apps/pull/612

**Comment by anishasthana** [comment]
@harshad16 any ideas? Seems like Juana only opened https://github.com/opendatahub-io/odh-manifests/issues/421

**Comment by harshad16** [comment]
The release bots opens tag based on the pattern vx.y.z 
the later  1.0.11 was not created by the bot.

I had asked about this to @nakfour , she mentioned the tag release 1.0.11 was just created for testing.
Both are proper as they reference the same commit, however the pattern vx.y.z would be more apt as that from the bot and it would continue to happen. 
@nakfour  might have a better and clear answer for this as a maintainer.

**Comment by LaVLaS** [comment]
As @harshad16 stated `v1.0.11` should be the official release. 

@tumido Does your upgrade pipeline trigger automatically based on the creation of any new tag/release?

**Comment by harshad16** [comment]
@LaVLaS yes those upgrade pipeline trigger automatically based on every tag release
same automation for rhods with different sets of operations.

**Comment by tumido** [comment]
Yup, we've got a PR for each of those releases :slightly_smiling_face: Maybe we should consider marking the "test" releases as a "pre-release" in github and triggering the CI from GH releases (filtering out the pre-releases) instead of direct tag pushes. WDYT?

**Comment by nakfour** [comment]
the 1.0.11 was my mistake, just use v1.0.11

**Comment by nakfour** [comment]
deleted the 1.0.11 tag
