### ISSUE TITLE
KF pipeline execution fails with "k8sapi executor does not support outputs from base image layer. must use emptyDir"

### ISSUE THREAD

**Issue by ptitzler** [opendatahub-io/odh-manifests#424]
**Describe the bug**
I've deployed Kubeflow using the latest ODH operator and the official `https://raw.githubusercontent.com/kubeflow/manifests/master/distributions/kfdef/kfctl_openshift.v1.2.0.yaml` without making any changes. I've also deployed JupyterHub/Elyra, created a pipeline, and ran it on the deployed KF instance. Pod execution fails in KFP with 
```
"invalid spec: templates.python-notebook.outputs.artifacts.mlpipeline-metrics: k8sapi executor does not support outputs from base image layer. must use emptyDir"
```

Since I've used the official/recommended kfDef I assumed that KF 1.2 with Argo would work without having to apply any workarounds.  (See related issue https://github.com/opendatahub-io/odh-manifests/issues/117). Is that assumption incorrect?

**Steps To Reproduce**
1. Deploy latest ODH operator
2. Use operator to deploy KF using https://raw.githubusercontent.com/kubeflow/manifests/master/distributions/kfdef/kfctl_openshift.v1.2.0.yaml
3. Try to run a pipeline
4. Pod execution fails with "k8sapi executor does not support outputs from base image layer. must use emptyDir"

**Expected behavior**

**Workaround (if any)**
Any manual steps that allow you to resolve the issue

**Open Data Hub Version**
Please attach relevant kfdef manifest if applicable

https://raw.githubusercontent.com/kubeflow/manifests/master/distributions/kfdef/kfctl_openshift.v1.2.0.yaml

**OpenShift Version**
Version #: 4.6.23_1540
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...): IBM Cloud

**Additional context**

**Comment by ptitzler** [comment]
Is KF 1.3 supported yet?

**Comment by nakfour** [comment]
@ptitzler yes we are aware of this issue with KFP on Argo, we even opened an issue here: https://github.com/kubeflow/pipelines/issues/4326
You can try KFP on Tekton using this example kfdef: https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_openshift.master.kfptekton.yaml
or KF 1.3 using this example kfdef: https://github.com/kubeflow/manifests/blob/master/distributions/kfdef/kfctl_openshift_v1.3.0.yaml

**Comment by ptitzler** [comment]
Neither one of the two KfDef deploys on RHOS 4.6.23_1540 on IBM Cloud

**Comment by ptitzler** [comment]
To be specific, I've tried deploying using ODH and using the instructions in https://www.kubeflow.org/docs/distributions/openshift/install-kubeflow/

It seems to fail getting istio up: [kfctl_apply_output.log](https://github.com/opendatahub-io/odh-manifests/files/6504831/kfctl_apply_output.log)

```
WARN[0066] Encountered error applying application istio-stack:  (kubeflow.error): Code 500 with message: Apply.Run : [error when applying patch:
...
Deployment.apps "istio-ingressgateway" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app":"istio-ingressgateway", "istio":"ingressgateway"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable, error when creating "/tmp/kout126430861": admission webhook "pilot.validation.istio.io" denied the request: configuration is invalid: envoy filter: missing filters]  filename="kustomize/kustomize.go:284"
WARN[0584] Will retry in 24 seconds.                     filename="kustomize/kustomize.go:285"
```

**Comment by nakfour** [comment]
Kubeflow 1.3 is currently only running on OCP 4.5. Issues for OCP 4.6/4.7 are documented here: https://github.com/kubeflow/manifests/issues/1867
