### ISSUE TITLE
CI/CD for Open Data Hub images

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/odh-manifests#43]
/cc @goern @crobby 

[This card](https://trello.com/c/YtlJk63G/994-13-odh-app-stack-ci-pipeline-nokr) from Thoth team describes how they would like to build a CI/CD pipeline around ODH images - starting with JupyterHub images.

Current design revolves around Tekton Pipelines hosted on *some* OpenShift instance.

The requirements are:

* The pipeline manifests are hosted under Open Data Hub and well documented so that anyone can reproduce the builds
* Builds are running publicly and the resulted images are hosted on Quay.io
* Builds are triggered automatically for PRs and push to a repository (build manifests and resources will probably live in various repositories)
* Build results are visible in PR and can be used for testing the PR and gating merge
* The pipeline needs to be able to handle Dockerfile as well as s2i builds

**Comment by goern** [comment]
@harshad16

**Comment by goern** [comment]
Please let us know which list of Jupyter images have what priorities, so that we can focus on them

**Comment by goern** [comment]
https://github.com/AICoE/s2i-custom-notebook/issues/4

**Comment by vpavlin** [comment]
Thoth images are now part of ODH - https://github.com/opendatahub-io/odh-manifests/pull/162
