### ISSUE TITLE
Ability to customize Jupyterhub Spawner Page UI options

### ISSUE THREAD

**Issue by altruistcoder** [opendatahub-io/odh-manifests#430]
Hello,

I have been working on the ODH project from quite a while now but I am stuck at a problem from some time.

Due to the specifications of the GPU nodes that my cluster consists of, **I have limitations of providing at max 1 GPU to any user**. Thus, I want to give users an option to choose only one GPU at max, **instead of a text box** where they can fill the number of GPUs they need for now. Thus, I want to have a **checkbox** where users can just tick whether they want to choose GPU or not instead of a textbox field where they can enter any number of GPUs they want.

In the version **v0.9 of ODH**, I was able to achieve this by modifying the code present in the **jupyterhub_config.py** file, updating the jupyterhub image and then using the updated image. I was able to do so because there was a part of the UI html tags that were being returned as response from the jupyterhub_config.py file which I modified to convert the text box field to a checkbox field and handled the values entered by the users in them, accordingly. I know this is a bad practice but it worked as a workaround for me then. For better understandability of the changes I made, I replaced the code written for textbox field with the following:

```
response += """
        <p>
            <label>Do you want GPU? </label>
            <input type="checkbox" value="1" name="gpu" />
        </p>
```

Now, the problem is I want to achieve the same purpose in the **updated version of ODH, i.e. v1.0** but I am **not able to do** it as I did it in the last version as there have been multiple changes both in the UI and the code present in the jupyterhub_config.py file.

I found out a source code repo of the UI present [here](https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/tree/master/jupyterhub_singleuser_profiles/ui/src) but I am **not sure if this the exact source code** being used in the Spawner Page UI. Also, if this is the actual source code being used, I am still **not sure where exactly I need to make the suitable changes** so that it gets reflected in the running Jupyterhub Pod's Spawner page UI in my cluster.

So, if you could please suggest me how can I achieve my target, then it would be really very helpful.

**Comment by mroman-redhat** [comment]
There is an upcoming version of ODH which includes the ability to modify the UI from the JSP Configmap. It is documented here: https://github.com/opendatahub-io/jupyterhub-singleuser-profiles/blob/master/docs/ui_configuration.md.
