### ISSUE TITLE
Unequal distribution of ODH Pods on multiple nodes

### ISSUE THREAD

**Issue by altruistcoder** [opendatahub-io/odh-manifests#431]
Hello,

I have been working on the ODH project for some time now and I have got an observation. There are a bunch of ODH instances running on my cluster across different Openshift namespaces each having its own set of Jupyterhub pods and all the nodes constituting my Openshift cluster are GPU nodes. 
While according to the ideal behavior, as soon as a new instance is created, the pods related to it must be scheduled to be placed on a node that has relatively lower amount of CPU & memory resources being consumed on them at that time as compared to other nodes. But, I have seen that this doesn't happen in my case and sometimes the newer pods keep getting scheduled on a node already having very low Memory or CPU resources left available on it and hence keeps filling up the same node to a great degree while some of the other nodes have comparatively larger amount of CPU & memory resources available on them.

If you could please give me some idea whether such behavior is an expected one?, Is it happening because the cluster consists of only GPU nodes for its worker nodes?, or there is something else which might be causing such behavior to be seen, then that would be really very helpful.

**Comment by nakfour** [comment]
@altruistcoder this is specific to Openshift scheduler and outside of scope for ODH. However, here is an interesting new feature in OCP 4.7 that is still tech preview. https://docs.openshift.com/container-platform/4.7/nodes/scheduling/nodes-scheduler-profiles.html that give you an option to pick how the scheduler works.
