### ISSUE TITLE
new cuda-ubi8-build-chain

### ISSUE THREAD

**Issue by Sg-23** [opendatahub-io/odh-manifests#433]
I have observed the earlier chain was [https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda/cuda-ubi7-build-chain.yaml] but the new chain (https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/cuda-11.0.3/cuda-ubi8-build-chain.yaml)  includes two more layers for s2i-core and s2i-base. Could you please provide some information where I can understand the use of each layer?

**Comment by dmarcus-wire** [comment]
These images come from RH software collection library. Here is the parent and the Dockerfiles for those images used in the build chain
NVIDIA - https://ngc.nvidia.com/catalog/containers/nvidia:cuda
parent - https://github.com/sclorg/s2i-base-container
s2i-core - https://github.com/sclorg/s2i-base-container/blob/master/core/Dockerfile.rhel8
s2i-base - https://github.com/sclorg/s2i-base-container/blob/master/base/Dockerfile.rhel8

The chain first pulls the image from NVIDIA 11.3.0-cudnn8-devel-ubi8 devel: Builds on the runtime and includes headers, development tools for building CUDA images. 
The s2i-core image provides any images layered on top of it with all the tools needed to use source-to-image (s2i). 
The s2i-base image, gets built on the s2i-core and provides libraries for other builder images like s2i-python, which is required for jupyter notebooks.
