### ISSUE TITLE
Update the opendatahub.io for 0.6

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/odh-manifests#46]
Match the channel names in the documentation on the website and provide quick install for 0.6 (Beta)

- [x] https://gitlab.com/opendatahub/opendatahub.io/-/merge_requests/70
- [x] https://gitlab.com/opendatahub/opendatahub.io/-/merge_requests/71
- [x] https://gitlab.com/opendatahub/opendatahub.io/-/merge_requests/72

**Comment by vpavlin** [comment]
- [ ] https://gitlab.com/opendatahub/opendatahub.io/-/merge_requests/70
- [ ] https://gitlab.com/opendatahub/opendatahub.io/-/merge_requests/72

**Comment by nakfour** [comment]
@nakfour  @LaVLaS please review
