### ISSUE TITLE
OpenDataHub 0.6 on IBM Cloud OpenShift 4.3

### ISSUE THREAD

**Issue by animeshsingh** [opendatahub-io/odh-manifests#50]
Document and test ODH 0.6 on IBM Cloud OpenShift 4.3 version

**Comment by animeshsingh** [comment]
@vpavlin @adrian555

**Comment by animeshsingh** [comment]
@adrian555 please give this a try once @vpavlin gives a go ahead that first version is ready to be tested

**Comment by vpavlin** [comment]
Hi @animeshsingh @adrian555, we are waiting for the community-operators PR to be merged (https://github.com/operator-framework/community-operators/pull/1637) and we have a few issues that need to be resolved (https://github.com/orgs/opendatahub-io/projects/3) to get 0.6.1 out - I would recommend to hold off with official documentation for 0.6.1. That said, you can definitely start testing now:)

@animeshsingh  Where do you plan to publish the documentation? 

Please let us know if you see any issues
