### ISSUE TITLE
JupyterHub ServiceAccount permissions breaking automatically

### ISSUE THREAD

**Issue by vemonet** [opendatahub-io/odh-manifests#527]
**Describe the bug**
I deployed a JupyterHub with GitHub login a few weeks ago. It was working fine, I could start my notebooks

But when I came back a few weeks after without doing a single change to the project, I am now getting this error when trying to deploy a notebook:

```
 Error: HTTP 500: Internal Server Error (Error in Authenticator.pre_spawn_start: ForbiddenError 403 Reason: error HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f832a95c-66f3-4a16-81f7-12dd46f4c085', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '1c8d3b08-c7cf-4e39-b24f-b3b0d783deab', 'X-Kubernetes-Pf-Prioritylevel-Uid': '502f2dec-904b-434b-aee7-87144b2ccead', 'Date': 'Thu, 17 Feb 2022 10:30:06 GMT', 'Content-Length': '283'}) HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},
"status":"Failure","message":"nodes is forbidden: User \\"system:serviceaccount:github:jupyterhub-hub\\" cannot list resource \\"nodes\\" in API group \\"\\" at the cluster scope","reason":"Forbidden","details":{"kind":"nodes"},"code":403}\n' Original traceback: File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", line 42, in inner resp = func(self, *args, **kwargs) File "/opt/app-root/lib/python3.6/site-packages/openshift/dynamic/client.py", 
line 247, in request _return_http_data_only=params.get('_return_http_data_only', True) File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 345, in call_api _preload_content, _request_timeout) File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 176, in __call_api _request_timeout=_request_timeout) File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 366, in request headers=headers) 
File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/rest.py", line 241, in GET query_params=query_params) File "/opt/app-root/lib/python3.6/site-packages/kubernetes/client/rest.py", line 231, in request raise ApiException(http_resp=r) ) 
```

Sorry for the long unreadable 1 line error, but that's how your JupyterHub operator is reporting issues (it should know better). From this error it seems the most interesting is:

```
,"status":"Failure","message":"nodes is forbidden: User \\"system:serviceaccount:github:jupyterhub-hub\\" cannot list resource \\"nodes\\" in API group \\"\\" at the cluster scope","reason":"Forbidden",
```

I did not touch the project, so it's most probably caused by your JupyterHub operator that is doing weird things with the service account and roles. How can we prevent it to do those automated things that breaks the system @LaVLaS @accorvin ?

Note the `jupyterhub-hub` service account still exists

**Steps To Reproduce**
1. Create a `github` project in your cluster
2. `git clone https://github.com/MaastrichtU-IDS/odh-manifests`
3. `cd odh-manifests/kfdef`
4. `./create_odh.sh kfctl_openshift_github.yaml`
5. Now it should work
6. Wait a few weeks without doing anything, you should now have the same problem (maybe)

**Expected behavior**
When I start a JupyterHub I expect it should still work a few weeks later

**Workaround (if any)**
Hoping to find one here!

**Open Data Hub Version**
https://github.com/MaastrichtU-IDS/odh-manifests/blob/dsri/kfdef/kfctl_openshift_github.yaml

**OpenShift Version**
Version #: OKD 4.6
Provider Baremetal

**Comment by LaVLaS** [comment]
@vemonet Can you confirm that this is resolved now that #545 has merged?  We have seen this issue pop up recently.  Is there only one JupyterHub deployment in your cluster?

**Comment by vemonet** [comment]
Hi @LaVLaS , thanks for the feedback, I will try when I have the time to go back to it (go again over the 1000 lines config files to make sure nothing has changed in the config, and redeploy our JupyterHubs)

There is no more JupyterHub deployment in our cluster 🙂

We also had another JupyterHub that was using the OpenShift login that was working for some months, but it stopped working also due to peer certificates issuer not recognized (not sure if it is something related to the certs in our infrastructure, or if it is related to the ODH deployment)

```
    HTTPServerRequest(protocol='https', host='apps.openshift.host', method='GET', uri='/hub/oauth_callback?code=sha256~f9', version='HTTP/1.1', remote_ip='####')
    Traceback (most recent call last):
      File "/opt/app-root/lib/python3.6/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/app-root/src/oauthenticator/oauthenticator/oauth2.py", line 356, in fetch
        resp = await self.http_client.fetch(req, **kwargs)
    tornado.curl_httpclient.CurlError: HTTP 599: Peer's Certificate issuer is not recognized.
```

**Comment by vemonet** [comment]
I am a bit surprised that when you have developed the Operator, you did not make sure that each object created was unique to the JupyterHub

It should be basic kubernetes best practices no? 

Otherwise you will get a lot of conflict all other the place in your cluster. The whole principle of container orchestration is starting containers in isolation, but we see mainly basic conflicts whenever we try to install "isolated" deployments on OpenShift using operators (even the operators vouched for by RedHat)

Is there other design choice like this we need to be aware of? Maybe OpenShift operators doesn't really support deploying multiple instances of the same deployment in general and we are using it wrong?

**Comment by vemonet** [comment]
Hi @LaVLaS 

I merged the changes in the `master` branch of this repo, and tried to cleanup the JupyterHubs on our cluster + re-deploy JupyterHub

But we are still getting the same error

You can easily find the changes we did here: https://github.com/MaastrichtU-IDS/odh-manifests/ on the `dsri` branch 


Note that since the beginning we have been using `kfctl` it never was able to actually delete the instance we created fully 

Doing a `kfctl delete` was taking **more than 10 min** to delete a few kubernetes objects (hahaha that's the worst thing I have ever seen in my life honestly, how is it possible to fail something so easy?)

```
ARN[0314] error evaluating kustomization manifest for odh-common: Timed out waiting for resource /anonymous to be deleted. Error deleted resource is not cleaned up yet  filename="kustomize/kustomize.go:459"
Error: couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for kustomize:  (kubeflow.error): Code 500 with message: error deleting kustomize manifests: error evaluating kustomization manifest for odh-common: Timed out waiting for resource /anonymous to be deleted. Error deleted resource is not cleaned up yet
Usage:
  kfctl delete [flags]

Flags:
      --delete_storage   Set if you want to delete app's storage cluster used for mlpipeline.
  -f, --file string      The local config file of KfDef.
      --force-deletion   force-deletion output default is false
  -h, --help             help for delete
  -V, --verbose          verbose output default is false

kfctl exited with error: couldn't delete KfApp:  (kubeflow.error): Code 500 with message: kfApp Delete failed for kustomize:  (kubeflow.error): Code 500 with message: error deleting kustomize manifests: error evaluating kustomization manifest for odh-common: Timed out waiting for resource /anonymous to be deleted. Error deleted resource is not cleaned up yet%    
```

So we are not sure if all the objects related to the ODH deployments are deleted. Are they? How can we check?

I needed to write a dirty wrapper script that is doing most of the tasks that should be handled by `kftctl`: fix the cache, remove dirty artefacts kfctl was adding to my commited kfdef files: https://github.com/MaastrichtU-IDS/odh-manifests/blob/dsri/kfdef/delete_odh.sh

Maybe you have other more efficient way to deploy? And especially delete the stack?

**Comment by vemonet** [comment]
@LaVLaS we just merged the changes from `odh-manifests` and it worked well, thanks a lot!
