### ISSUE TITLE
Yaml Linting Rules

### ISSUE THREAD

**Issue by Gregory-Pereira** [opendatahub-io/odh-manifests#542]
**Is your feature request related to a problem? Please describe.**
When maintaining a fork of `odh-manifests` it would be nice to have linting rules to ensure cleanliness of contribution to the repository. As we work mostly on a downstream fork, this is not something we would like to implement ourselves, otherwise we would be sacrificing our shared history with the `opendatahub-io` remote, or pulling from a tag, and then adding a commit that modifies and lints many previous commits.

**Describe the solution you'd like**
An implementation of yaml-linting rules that can be run as a check on pull requests in the repository. In `operate-first` we use prow ([see our configuration](https://github.com/operate-first/apps/blob/master/.prow.yaml#L21-L39)) to run [our pre-commit rules](https://github.com/operate-first/apps/blob/master/.pre-commit-config.yaml#L4-L29) and [yaml-lint rules](https://github.com/operate-first/apps/blob/master/yamllint-config.yaml).

**Additional context**
Any form of linting rules would be nice, I have simply offered some examples of what we use for context.

**Comment by LaVLaS** [comment]
@mlassak Per our discussion, we should be able to use [kube-linter](https://github.com/stackrox/kube-linter) for yamlint and linting k8s manifests
