### ISSUE TITLE
Jupyterhub failing to deploying using custom kfdef in openshift 4.9

### ISSUE THREAD

**Issue by akchinSTC** [opendatahub-io/odh-manifests#558]
**Describe the bug**
Following the instructions here

![image](https://user-images.githubusercontent.com/13340013/165638718-4c03c8ad-7619-4cb7-bf1b-c2b9b5e78b1a.png)

the jupyterhub pod fails to deploy using the following KFdef
https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_openshift4.9_odh.yaml

![image](https://user-images.githubusercontent.com/13340013/165639126-25098d1f-3fc4-4fbe-abea-901132c1c398.png)

full log output of the failing deployment pod:
```
error: error executing jsonpath "{.items[0].metadata.labels.deployment}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.labels.deployment}
	object given to jsonpath engine was:
		map[string]interface {}{"apiVersion":"v1", "items":[]interface {}{}, "kind":"List", "metadata":map[string]interface {}{"resourceVersion":"", "selfLink":""}}


Warning: Couldn't read data from file "", this makes an empty POST.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   400  100   400    0     0    318      0  0:00:01  0:00:01 --:--:--   318
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {

  },
  "status": "Failure",
  "message": "replicationcontrollers is forbidden: User \"system:serviceaccount:opendatahub:deployer\" cannot update resource \"replicationcontrollers/tmp\" in API group \"\" in the namespace \"opendatahub\"",
  "reason": "Forbidden",
  "details": {
    "kind": "replicationcontrollers"
  },
  "code": 403
}  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0100   555  100   425  100   130   1070    327 --:--:-- --:--:-- --:--:--  1394
{
  "kind": "Scale",
  "apiVersion": "autoscaling/v1",
  "metadata": {
    "name": "jupyterhub-1",
    "namespace": "opendatahub",
    "uid": "6f0a2876-4060-40fd-a082-c6eace745a5a",
    "resourceVersion": "41042",
    "creationTimestamp": "2022-04-27T21:22:04Z"
  },
  "spec": {
    "replicas": 3
  },
  "status": {
    "replicas": 0,
    "selector": "app=jupyterhub,deployment=jupyterhub-1,deploymentconfig=jupyterhub"
  }
}
```
**Steps To Reproduce**
1. Create openshift 4.9.x cluster on ibm cloud
2. create new project opendatahub and Install operator 
3. use the link for the updated kfdef that only deploys jupyterhub
4. See error during deployment

![image](https://user-images.githubusercontent.com/13340013/165638718-4c03c8ad-7619-4cb7-bf1b-c2b9b5e78b1a.png)

**Expected behavior**
Jupyterhub deployment to succeed and start

**Workaround (if any)**
Any manual steps that allow you to resolve the issue

**Open Data Hub Version**
https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_openshift4.9_odh.yaml

**OpenShift Version**
![image](https://user-images.githubusercontent.com/13340013/165639697-4e526d18-5ccc-424f-a69e-5fa25ecb0cfb.png)
**Additional context**

**Comment by LaVLaS** [comment]
Closing this since JupyterHub was deprecated in ODH 1.5 release
