### ISSUE TITLE
Migration of ODH Contrib Tier 2 components to new organization

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-manifests#577]
As we move to re-architect ODH and its components, we want to provide clear guidance on the support level of components that will be part of the ODH Core (Tier 0) offering with full long term support vs ODH Contrib (Tier 2) components that are solely maintained by the designated maintainer with no limited support.

New GitHub organization for ODH Contrib (Tier 2) - https://github.com/opendatahub-io-contrib
- [x] #586
- [ ] Move `odhpachyderm` to ODH Tier 2 organization
- [ ] Move `trino` to ODH Tier 2 organization
- [ ] Move `superset` to ODH Tier 2 organization
- [ ] Move `openshift-service-mesh` to ODH Tier2 organization
- [ ] Move `odhargo` to ODH Tier 2 organization
- [ ] Move `odhseldon` to ODH Tier 2 organization
- [ ] Move `openshift-pipelines` to ODH Tier 2 organization
- [ ] Move `kafka` to ODH Tier 2 organization
- [x] #640
- [ ] Move `radanalyticsio` to ODH Tier 2 organization
- [ ] Move `ceph-nano` to ODH Tier 2 organization
- [ ] Move `hue` to ODH Tier 2 organization
- [ ] Move `thriftserver` to ODH Tier 2 organization

Below is the list of components provided in currently availaible in odh-manifests and where we expect them to exists once the ODH Re-architecture is complete.  Ti The initial migration will still support the deployment of these components using ODH Operator `kfdef` custom resources

ODH Core (TIER 0)
===
- odh-dashboard
- jupyterhub
- odh-notebook-controller

ODH Incubating (TIER 1)
===
- model-mesh
- grafana
- prometheus

ODH Contrib (TIER 2) - github.com/opendatahub-io-contrib
===
- odhpachyderm
- google-spark-operator
- airflow helm chart
- trino
- superset
- openshift-service-mesh
- odhargo

ODH Contrib (TIER 2 - DEPRECATED) - github.com/opendatahub-io-contrib
===
- Provided by OperatorHub -  odhseldon, openshift-pipelines, kafka
- ai-library
- radanalyticsio
- ceph-nano - Possible replacement by noobaa-operator
- hue
- thriftserver

**Comment by Zveroloff** [comment]
Would this new org be open for contribution?

**Comment by anishasthana** [comment]
@LaVLaS this issue makes no mention of pipelines. Also... would we want to move JupyterHub out of odh-core going forward?

**Comment by LaVLaS** [comment]
> Would this new org be open for contribution?
@Zveroloff Yes we will provide guidance on the requirements and criteria for Tier 2 components

> @LaVLaS this issue makes no mention of pipelines. Also... would we want to move JupyterHub out of odh-core going forward?
@anishasthana openshift-pipelines is mentioned to move to Tier 2 since it is available for deployment via OperatorHub. Yes when the KFNBC and Dashboard UI is feature complete it would be moved out at a future date

> Up to now, a big pro in terms of integration is that most components are living under and are tested under the Red Hat / openshift / Open Data Hub Roof. I see this move a bit sceptical, e.g. with regards to Jupyter, Airflow, and Spark.
@shalberd 
- Jupyter notebooks will be fully supported but we are deprecating the JupyterHub server in favor of the KF Notebook Controller to provide better flexibility in managing notebooks inf Kubernetes environments 
- Current components of Spark operator and Airflow Operator are based on upstream projects that are out of date and no longer maintained by their respective community which is why they are being moved to Tier 2 for deprecation.  While we don't have any plans to support either as part of our `ODH Core (Tier 0)` deployment, we do have community members that have agreed to [limited] support for for each project under our ODH Contrib (Tier 2) organization

**Comment by shalberd** [comment]
Hello Landon @LaVLaS, thank you for your answers. The move to KF notebook controller is a very good one, however, will open issues for juypterhub-odh, such as proxy env configuration in templates and custom PKI CA trust configmap support still be implemented? Elyra for example would depend on such an http proxy env being available in the spawned container if they were to allow handling custom pipeline component downloads though http/https enterprise proxies. For my use case, I have managed to use an internal package repo that is accessible even without the enterprise-internal proxy, but still ... Moreover, the internal Artifactory or Sonatype Nexus have custom PKI CAs for Https/SSL.

https://github.com/opendatahub-io/jupyterhub-odh/issues/137
https://github.com/elyra-ai/elyra/issues/2787#issuecomment-1163096274

Regarding Airflow, we want to use Airflow 2.x in the future anyways, so going with the operator is not an option anymore given the state of development. We will use [Helm-Chart deployment ](https://airflow.apache.org/docs/helm-chart/stable/index.html) instead, which is fine for our purposes, though sad to see that the better operator approach is not followed by the airflow folks.
