### ISSUE TITLE
Notebook CRD exceeds size limits

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/odh-manifests#601]
**Describe the bug**
Notebook CRD too big, we might be hitting an issue where the CRD exceeds size limit . `kubectl` apply doesn't work and operator is stuck for subsequent reconciliation

**Steps To Reproduce**
1. Install Open Data Hub operator 
2. Deploy https://github.com/opendatahub-io/odh-manifests/blob/master/kfdef/kfctl_odh_notebook_controller.yaml
3. Deploy any other KfDef

**Expected behavior**
All KfDefs are deployed

**Workaround (if any)**
Restart operator pod

**Comment by samuelvl** [comment]
I can't reproduce the issue with kubectl, I think this is a problem related with kfctl:

``` 
kustomize build odh-notebook-controller/base | kubectl apply -f -
```

**Comment by VaishnaviHire** [comment]
> I can't reproduce the issue with kubectl, I think this is a problem related with kfctl:
> 
> ```
> kustomize build odh-notebook-controller/base | kubectl apply -f -
> ```

So we are seeing this in kfctl, because it is a `client-side apply`. The issue doesn't occur in server-side apply

**Comment by samuelvl** [comment]
@VaishnaviHire I see, can we fix this in kfctl code?

**Comment by samuelvl** [comment]
Fixed in https://github.com/opendatahub-io/opendatahub-operator/pull/171

**Comment by andrewballantyne** [comment]
@VaishnaviHire @samuelvl looks like the opendatahub-operator PR is approved but is on hold for unspecified reasons. Can we unhold it and get it merged to resolve this issue?
