### ISSUE TITLE
Kubeflow pytorch-operator integration

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/odh-manifests#65]
Summary
Integrate the KF pytorch-operator as a component in Open Data Hub

User Story
We have an internal use case for prioritizing integration of the PyTorch operator from Kubeflow.

Other information
OCP requirements

UBI image for operator
s2i generation of pytorch master and worker images
finalizers required in ClusterRole
anyuid currently, so need a conformant image build for UID

https://github.com/kubeflow/pytorch-operator

migrated from https://gitlab.com/opendatahub/opendatahub-operator/-/issues/214

**Comment by vpavlin** [comment]
Finalizers and UIDs solved in https://github.com/kubeflow/pytorch-operator/pull/276/files
