### ISSUE TITLE
Argo Events in ODH

### ISSUE THREAD

**Issue by nakfour** [opendatahub-io/odh-manifests#66]
Summary
Add Argo-events to ODH.
https://github.com/argoproj/argo-events

User Story
Add role for installing Argo-events. Since Argo is already added to ODH, to make complete AI pipeline some users might want to use Argo-events to reduce manual steps.

Other information
Installation: https://argoproj.github.io/argo-events/installation/
About: https://github.com/argoproj/argo-events

migrated from https://gitlab.com/opendatahub/opendatahub-operator/-/issues/208

**Comment by anishasthana** [comment]
cc @tumido. You already have manifests for deploying argo events right?
