### ISSUE TITLE
[KFNBC]: Openshift Monitoring does not display usage data for Jupyter notebooks 

### ISSUE THREAD

**Issue by lugi0** [opendatahub-io/odh-manifests#662]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After running a workload in a notebook server, openshift monitoring does not show any data 
![selenium-screenshot-92](https://user-images.githubusercontent.com/82518733/181280198-b4275de6-253b-48a1-91a3-6b47514bafa7.png)

### Expected Behavior

CPU usage data should be collected and shown

### Steps To Reproduce

Install RHODS 1.15 build with KFNBC
Enable KFNBC
Run a workload for a few minutes (e.g. 5 minutes)
Check CPU usage data from Openshift Monitoring with the query `cluster:usage:consumption:rhods:cpu:seconds:rate1h`

**Comment by andrewballantyne** [comment]
Not a ODH Dashboard issue, moved to ODH Manifests repo. See downstream PR https://github.com/red-hat-data-services/odh-manifests/pull/231

**Comment by LaVLaS** [comment]
Closing this issues due to the age. If this is still an issue, please file open a new issue in https://github.com/opendatahub-io/opendatahub-community/issues
