### ISSUE TITLE
Add ML Pipelines component to ODH

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-manifests#670]
Add the ML Pipelines component to Open Data Hub

- [ ] Release notes for the current version
- [ ] Link to any changelog
- [x] #637

**Comment by LaVLaS** [comment]
@rimolive @gmfrasca Just to confirm that the current version of ML Pipelines is based on the [v1.3.1](https://github.com/kubeflow/kfp-tekton/releases/tag/v1.3.1) release of KFP Tekton, correct?

**Comment by rimolive** [comment]
That's correct.
