### ISSUE TITLE
Move 'notebook-images' out of jupyterhub

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/odh-manifests#671]
`Notebook-images` is being used by both jupyterhub and notebook-controller components. 

Since we are moving away from jupyterhub, move [notebook-images](https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images) to the root folder.

**Comment by LaVLaS** [comment]
@samuelvl Do you think we are ready to switch to the ODH Core builds of the default notebook images?  If not we should create a new odh-core `notebook-images` manifest with the same structure and Imagestream names that will be used when the odh-core notebook images are built and available

**Comment by samuelvl** [comment]
@LaVLaS Most of the notebooks in `notebook-images` folder are outdated. The only images that [are compatible](https://github.com/opendatahub-io/odh-manifests/tree/master/tests/resources/notebook-controller/notebooks) with the notebook controller are [Thoth minimal](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/additional/minimal-notebook-imagestream.yaml) and [Thoth generic](https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/additional/generic-data-science-notebook-imagestream.yaml). I would only move these images to the notebook-images root folder as a short-term solution.

As we have talked in the community meeting, the mid-term plan is replacing Thoth images with a new set of notebooks for tier 0:

- py38-minimal
- py38-data-science
- py38-cuda
- py38-pytorch
- py38-tensorflow

These images will be stored in a new repository (https://github.com/opendatahub-io/notebooks) and will be built with Openshift CI and mirrored to Quay (https://quay.io/repository/opendatahub/notebooks).

cc @atheo89

**Comment by VaishnaviHire** [comment]
@samuelvl For jupyterhub we have been using [additional](https://github.com/opendatahub-io/odh-manifests/tree/master/jupyterhub/notebook-images/overlays/additional) overlay that includes updated elyra image as well. Should we exclude elyra when moving to root folder ?

**Comment by samuelvl** [comment]
@VaishnaviHire Elyra is not compatible with the notebook controller https://github.com/opendatahub-io/s2i-lab-elyra/issues/44

@LaVLaS Is the Elyra nootebok a Tier 0 component?

**Comment by LaVLaS** [comment]
The expectation is that Elyra is a Tier 0 notebook.

@romeokienzler Do you have any plans to update the Elyra notebook image to work with KFNBC?

**Comment by ptitzler** [comment]
We already do publish container images that run as notebook servers on Kubeflow: https://elyra.readthedocs.io/en/latest/recipes/using-elyra-with-kubeflow-notebook-server.html

**Comment by samuelvl** [comment]
@atheo89
