### ISSUE TITLE
Documentation on components status and tier in each version of ODH

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-manifests#687]
**Is your feature request related to a problem? Please describe.**
Currently there is no public documentation on the development status of each component in the odh-manifests or the tiers that the component belong to.

It would be great to get some sort of matrix that details information such as the version of each component in each release of ODH, the tier that it belongs to, and the status of that component in the release.

**Describe the solution you'd like**

The matrix that OpenShift GitOps provides in their release notes is a great example that showcases which version of each component is installed in each version of GitOps along with it's TP/GA status.

https://docs.openshift.com/container-platform/4.11/cicd/gitops/gitops-release-notes.html#compatibility-and-support-matrix

For ODH some sort of matrix like this could provide that information:

Tier 0 Components |   |   |   |   |  
-- | -- | -- | -- | -- | --
ODH Version | ODH-Dashboard | JupyterHub | Notebook Controller | Data Science Pipelines | Model Mesh
1.5 | 2.2.1 - GA | 0.3.8 - Depreciated | x.x.x - Under Development | x.x.x - Under Development | x.x.x - Under Development

Tier 1 Components |  
-- | --
ODH Version | Component
1.5 | x.x.x - GA

Tier 2 Components |   |   |  
-- | -- | -- | --
ODH Version | Airflow | Trino | Radanalytics
1.5 | [x.x.x](https://github.com/opendatahub-io-contrib/airflow-on-openshift) | x.x.x | x.x.x - Depreciated

The Tier 2 components are in a bit of a weird place since they do still exist in the odh-manifests repo but will be removed at some point.  But we could still use this as a location to link to the Tier 2 components in the contrib organization.

**Describe alternatives you've considered**

**Additional context**

**Comment by LaVLaS** [comment]
@strangiato Thx for the suggestion.  I think I'll add this to #672.  The tier2 components will not are separate components that will not be included/advertised as part of "ODH Core" under the opendatahub-io org but want to include that Tier 2 info as part of the [odh-contirb-manifests](https://github.com/opendatahub-io-contrib/odh-contrib-manifests) README
