### ISSUE TITLE
Not able to launch notebook

### ISSUE THREAD

**Issue by arpitsharma-vw** [opendatahub-io/odh-manifests#716]
Hello Team,
I have created the notebook instance as mentioned on the link:
https://github.com/opendatahub-io/odh-manifests/blob/master/odh-notebook-controller/README.md#creating-notebooks
But I see error`HTTP ERROR 502` on browser when try to access notebook. I dont see any error in notebook container while oauth proxy container shows error as `reverseproxy.go:490: http: proxy error: dial tcp [::1]:8888: connect: connection refused`. Can you help here?Thanks

**Comment by LaVLaS** [comment]
@arpitsharma-vw If you are still experiencing issues please let us know by filing an issues in https://github.com/opendatahub-io/opendatahub-community/issues
