### ISSUE TITLE
JupyterHub image from quay

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-manifests#73]
## User Story

As a OpenDataHub Operator, I want to pull JupyterHub images from quay so that I always have the latest and greatest version used by my deployment.

Please include the following images, rather than building them during deploy of JupyterHub:

- https://quay.io/repository/thoth-station/s2i-tensorflow-notebook
- https://quay.io/repository/thoth-station/s2i-scipy-notebook
- https://quay.io/repository/thoth-station/s2i-minimal-notebook

See Also https://trello.com/c/rZVislQV

gitlab issue - https://gitlab.com/opendatahub/opendatahub-operator/-/issues/218

**Comment by goern** [comment]
@harshad16

**Comment by harshad16** [comment]
workon-by : https://github.com/opendatahub-io/odh-manifests/pull/162

**Comment by goern** [comment]
is this done?

**Comment by vpavlin** [comment]
Almost, I think the last bit is to change URLs in the BuildConfigs that we have - I would like to keep those for development for now. I'll change those tomorrow and probably close this
