### ISSUE TITLE
Use ODH Core component test framework from their respective repositories as part of the integration tests

### ISSUE THREAD

**Issue by LaVLaS** [opendatahub-io/odh-manifests#736]
**Is your feature request related to a problem? Please describe.**
Currently we rely on standalone [basictests](https://github.com/opendatahub-io/odh-manifests/tree/master/tests/basictests) in odh-manifests to verify component deployments and check basic functionality.  Since they are separate from the component repos, they require additional effort to keep them updated with each component release.

We should utilize the test framework that each component is maintaining in their respective repos for the basic test framework before we utilize a full E2E testsuite for the integration testing.  These component tests would have to support testing against existing deployments to verify end user functionality.

**Describe alternatives you've considered**
Current method of having a separate testsuite to verify functionality of components when deployed via kfdef and is maintained separately from the component test suite

**Additional context**
These tests would be in addition to the full E2E integration testsuite that is maintained by QE.  
The expectation is the component testsuites would support running against an existing deployment to test user functionality

**Comment by HumairAK** [comment]
@harshad16 fyi
