### ISSUE TITLE
ServiceMonitor for "cluster metrics" leads to duplicate time series in cluster prometheus.

### ISSUE THREAD

**Issue by VannTen** [opendatahub-io/odh-manifests#750]
The ServiceMonitor we added in #732 is picked up by the Openshift cluster monitoring (aka, the prometheus inside `openshift-monitoring`).

https://github.com/opendatahub-io/odh-manifests/pull/732/files#diff-65c08348b44d9671833efb8fe315a0f860a7063cde788b6428b00c0ecb09a403

This is problematic beacuse we're basically telling Prometheus to scrap it's own federate endpoint -> obviously we're gonna have duplicates.

@anishasthana 
@VedantMahabaleshwarkar 

Workarounds:
- Remove the  `openshift.io/cluster-monitoring=true` lfrpm redhat-ods-monitoring namespace (it is intented btw ?)

A proper resolution could be to put those service monitor in the modelmesh prometheus config instead, using static_configs.

(And we should also probably limit the metrics to the one concerned by RHODS, because there is no need to get them from everything on the cluster)

https://issues.redhat.com/browse/RHODS-7570 prompted this.

**Comment by VannTen** [comment]
re-examining, this is a downstream issue, will fix it there

**Comment by shalberd** [comment]
Maybe you could see if instead, in RHODS, you could use the other (implied) namespace label for user monitoring.

https://docs.openshift.com/container-platform/4.9/monitoring/enabling-monitoring-for-user-defined-projects.html#excluding-a-user-defined-project-from-monitoring_enabling-monitoring-for-user-defined-projects

That way, you could remove openshift.io/cluster-monitoring=true  from redhat-ods-monitoring namespace and possibly still get to the metrics, just via the prometheus in openshift-user-workload-monitoring. Alerts all go through central alertmanager anyways in the concept of Monitoring for User Defined Projects. If that woudl help with telemetry, the alerts going though central openshift-monitoring, then this path would be better IMO. 

Here is how to enable Monitoring for User Defined Projects:

https://docs.openshift.com/container-platform/4.9/monitoring/enabling-monitoring-for-user-defined-projects.html#enabling-monitoring-for-user-defined-projects_enabling-monitoring-for-user-defined-projects
