### ISSUE TITLE
Unable to authenticate to OAuth Proxy with Service Account

### ISSUE THREAD

**Issue by strangiato** [opendatahub-io/odh-manifests#757]
**Describe the bug**
If a Service Account is granted a narrow scope to get services in the specific namespace that the opendatahub instance is deployed it will be unable to authenticate to with the OAuth Proxy instance.  With the current `--openshift-delegate-url` arg the Service Account must have cluster level permissions to view all services on the cluster.

**Steps To Reproduce**
1. Install ODH with a standard kfdef in a namespace called `opendatahub`
2. Create a test service account:
```
oc create sa test-connection
```
3. Grant permissions to the service account:
```
oc policy add-role-to-user view system:serviceaccount:opendatahub:test-connection
```
4. Verify SA has permissions to list service:
```
oc login --token=$(oc create token test-connection -n opendatahub)
oc get services ds-pipeline-ui -n opendatahub
```
5.  Attempt to authenticate to OAuth
```
URL='https://ds-pipelines-ui.route.com/apis/v1beta1/experiments' 
curl --location --request GET $URL \
--header "Authorization: Bearer $(oc create token test-connection -n opendatahub)" -I
```

Curl will return a 403 error message

**Expected behavior**
Should return a 200 message

**Workaround (if any)**
Any manual steps that allow you to resolve the issue
Grant the SA view permissions on all services for the entire cluster.

**Open Data Hub Version**
Please attach relevant kfdef manifest if applicable

**OpenShift Version**
Version #: 1.4.2
demo.redhat.com

**Additional context**

**Comment by shalberd** [comment]
@sabre1041  @strangiato Very awesome and so architecturally sound, great find not having to have cluster-level privileges anymore. 

https://github.com/opendatahub-io/odh-manifests/tree/master/odh-dashboard/base

Would the RBAC in odh-dashboard be changed, too, with regards to the auth-delegator clusterrole?
Similar to PR 700?
https://github.com/opendatahub-io/odh-manifests/pull/744/files


https://github.com/opendatahub-io/odh-manifests/blob/master/odh-dashboard/base/auth-delegator.clusterrolebinding.yaml

@andrewballantyne It could well be that there is, in terms of RBAC and role bindings, some overlap or potential for improvements in the manifests.
