### ISSUE TITLE
Update version for notebook controllers to v1.6.1-2

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/odh-manifests#779]
**Is your feature request related to a problem? Please describe.**
Update `odh-notebook-controller` and `kubeflow-notebook-controller` to release v1.6.1-2

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by harshad16** [comment]
Closing this issue.

Now the notebook-controller is updated 
and Currently, the update to v1.7.0-1 is in progress.
https://github.com/opendatahub-io/odh-manifests/pull/875

thanks for all the work.
