### ISSUE TITLE
Investigate IBM Cuda enabled UBI based image

### ISSUE THREAD

**Issue by vpavlin** [opendatahub-io/odh-manifests#79]
IBM provides CUDA enabled images for x86 and ppc64le in RH registry - https://access.redhat.com/containers/#/product/18c03ee6ba6a3657

It might be interesting to experiment with this for CUDA enable jupyter notebook images instead of asking a user to build the whole chain in OpenShift on deployment

**Comment by goern** [comment]
@harshad16 @sub-mod
