### ISSUE TITLE
allow for specifying imagepullsecret for all serviceaccounts, context is disconnected with separate external docker registry

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-manifests#833]
**Is your feature request related to a problem? Please describe.**
External docker registries in enterprise contexts often do not allow anonymous access and pulling. 
Enterprise users typically create a type:dockerconfigjson secret and then link the secret to the default serviceaccount for each projects for pull.

https://stackoverflow.com/questions/52320090/automatically-add-imagepullsecrets-to-a-serviceaccount

ODH applications use serviceaccounts. For supporting pulling images from external registries, add the following to all kind: ServiceAccount specs here. @andrewballantyne depending on whether serviceaccount names of notebooks are dynamic, you would need to optionally support this, too:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: odh-dashboard 
imagePullSecrets:
  - name: private-registry-docker-pull-secret
```

Background explained [here](https://docs.openshift.com/container-platform/4.10/openshift_images/managing_images/using-image-pull-secrets.html#images-allow-pods-to-reference-images-from-secure-registries_using-image-pull-secrets): "To use a secret for pulling images for pods, you must add the secret to your service account. The name of the service account in this example should match the name of the service account the pod uses."

You can either do that at the command-line with 
`oc secrets link  <service_account_name> <pull_secret_name> --for=pull`
or via yaml as described above.

Because the mirrored location differs at each customer that uses private enterprise repos like VMWareHarbor or Artifactory for mirroring docker images to and because secret names are managed by the customer, the name of the imagePullSecret would need to be parametrizable. In the case of odh-manifests, best via KfDef parameter for each component. In the case of dynamically-created serviceaccounts, a configmap key like privateRegistryDockerPullSecret could be used and then referred to in program code then creating the spec of the serviceaccount.

**Describe the solution you'd like**
If the customer wants to, they can link an dockerconfigjson image pull secret to each serviceaccount so that images can be pulled authorized.

**Describe alternatives you've considered**

- Manually modifying the manifests
- Having cluster-admins add a [global pull secret](https://cloud.ibm.com/docs/openshift?topic=openshift-registry#cluster_global_pull_secret) that is valid on each worker node. Often times, with different teams on a multi-tenant cluster, different parts of the repo are supposed to be available only to certain namespaces / projects in openshift and not globabally. In that case, one has to link the pull secret to all serviceaccounts (default and application-specific) in a namespace.

**Additional context**
Could also be an issue when a lot of downloads happen from repos like dockerhub ... at some point in time, only authenticated docker image pulls are allowed ([rate limit](https://docs.docker.com/docker-hub/download-rate-limit/))
I guess less likely with quai.io and your very dynamic ip ranges and non long-running clusters.

**Comment by andrewballantyne** [comment]
Thanks for logging this Sven. This is an interesting configuration -- since it's a cluster-wide configuration but created per Namespace and used in every Notebook (service account) -- this means it needs to be an Admin configuration to setup the repo and credentials.

This is somewhat a configuration problem from permissions because we don't really let user-generated items be used in all namespaces. Would need to think through a bit how the logistics of that could work out.

If you have thought about this already, let me know what your thoughts are.

**Comment by shalberd** [comment]
Yes, setting up the repo and credentials is an Admin task, which is why we do not cover it here. 
Yet, when the repo needs authentication, we need to link serviceaccounts, be it the default serviceaccount or application-specific serviceaccounts, in each namespace to the image pull secret. 

The problem is: often, with option, like tolerations for node taints or node selectors, those can be set at the namespace-level. But this image pull secret cannot be set at a namespace-level for all serviceaccounts, it really has to be linked to each and every serviceaccount manually.

@Jooho what do you think?

**Comment by shalberd** [comment]
@andrewballantyne @rhefner 

Regarding image pull secrets created per namespace linked to service accounts, I see some similiarities conceptually in how you currently handle tolerations as well.

Similarity 1:

I see that in general, you only support annotations and config additions at a notebook-level via ODH dashboard config, not at a namespace-level. 

Regarding e.g. a tolerations annotation, which could also be done at namespace / project level, @andrewballantyne  mentioned on Slack on May 29: 

"We only support Tolerations for “notebooks” (aka Project “Workbenches”) — which will still need the accompanying Taint on the node. There is a UI option for this one — if you’re an admin you can see it in the Settings => Cluster Settings section of the Dashboard" Though I don't know how `notebookTolerationSettings` with key-only would support a key-value type annotation for tolerations, as that [always has value and e.g. NoExecute and Equals](https://docs.openshift.com/container-platform/4.10/nodes/scheduling/nodes-scheduler-taints-tolerations.html)

With our relatively static projects / namespaces, we would prefer to add toleration annotations on a data science project level instead of worbench / notebook level, but I see that when it comes to pod placement on nodes that have GPU or not GPU, it can be valuable to not add the toleration at level namespace for all pods / notebooks. For other cases, a toleration for all pods in a project could be easier.

Similarity 2: 

For the tolerations, you mention that the nodes themselves need to be tainted by a cluster-admin. Yes, true.

That can be done for image pull secrets, too, that is, for all service accounts in all namespaces, globally. But, as I said, that global pull secret for subpaths of private docker repos is often not done centrally, because we do not want authentication to be possible across namespaces.

So, what we do it we add the same docker secret to all relevant namespaces, which in your case would be all data science projects.

Then, we link that secret to all service accounts in that namespace, so that images can be pulled from the private repo / subpath, e.g. myvmwareharbor.swiss/myrepo

So, since you add tolerations to each workbench / notebook / statefulset / pod, and since each notebook pod has a uniquely-named serviceaccount, you could add a setting in the settings - clustersettings for [adding a pull secret]([https://docs.openshift.com/container-platform/4.10/openshift_images/managing_images/using-image-pull-secrets.html#images-allow-pods-to-reference-images-from-secure-registries_using-image-pull-secrets] with

- docker-server e.g. myvmwareharbor.swiss/myrepo
- docker-username
- docker-password

and either create a dockerconfig json from that or directly create a secret with that info. Then, programatically, at that pull secret to each data science project namespace upon namespace creation. Plus, you can then add that secret by name (link it for pull) to all serviceaccounts in imagePullSecrets section of the notebooks / workbenches' service account, as the service account is created.

The question is: who can view OdhDashboardConfig? And can settings from there be transported over the the non-dashboard data science project namespaces?

**Comment by shalberd** [comment]
Regarding dynamically-created notebooks and odh-dashboard and image pull secret, there is an additional possibility:

[putting imagePullSecrets in the PodSpec](https://docs.openshift.com/container-platform/4.10/rest_api/template_apis/podtemplate-v1.html#template-spec-imagepullsecrets) instead of linking it to the service account name that the pod runs under. But since both podSpec part of the notebook and serviceaccounts part are put together dynamically during assembleNotebook, it does not make a difference in my opinion.

**Comment by shalberd** [comment]
I will submit a PR here in odh-manifests for those applications (model mesh controller, dashboard, notebook controller, odh notebook controller ... ) that are using static serviceaccounts in the main opendatahub namespace as well as here for manifests. Mere changes to manifests with kustomize tweaks. Focussing on that first, made it work with a local copy of the modified manifests tarball already.

@andrewballantyne  For odh-dashboard notebooks, we will need to figure out a way to 
a) add image pull secret with dockerconfigjson credentials to a dynamic workbench namespace
b) link up that image pull secret by name with the dynamically-created serviceaccounts

That will be a PR for odh-dashboard, will propose later.

**Comment by shalberd** [comment]
@VaishnaviHire can someone add a milestone tag to this issue in terms of planning, e.g. v1.7?

**Comment by LaVLaS** [comment]
> @VaishnaviHire can someone add a milestone tag to this issue in terms of planning, e.g. v1.7?

We will do an initial review this issue and PR then decide which milestone it would be available in based on currently planned workload
