### ISSUE TITLE
assemblePVC with storageclass name not working in DSP / frontend

### ISSUE THREAD

**Issue by shalberd** [opendatahub-io/odh-manifests#840]
**Describe the bug**

When creating a workbench in a data science project, the underlying PVC does not look at the storageclassname from odhconfig. That leads to all other steps failing, only the PV is listed, but in PVC openshift console view, there is a message:

storageclassname not set
![Bildschirmfoto 2023-06-08 um 17 32 54](https://github.com/opendatahub-io/odh-manifests/assets/21118431/4a506691-b968-4a8a-a46c-234b2ca7d27b)

![Bildschirmfoto 2023-06-08 um 17 13 14](https://github.com/opendatahub-io/odh-manifests/assets/21118431/50e65ad1-7db4-4b45-b920-5cded82c2397)

https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/api/k8s/pvcs.ts#L13

https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/projects/screens/spawner/service.ts#L45

however, in assembleNotebook in backend code for the Jupyter tile, all is working as expected:

https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/notebookUtils.ts#L590

https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/notebookUtils.ts#L610

**Steps To Reproduce**

**Expected behavior**
a PVC with storageclassname as set in ODH Dashboard Config is created when working from Data Science Projects workbench creation; with frontend code, similar to backend code

**Workaround (if any)**
Any manual steps that allow you to resolve the issue

**Open Data Hub Version**
1.6.0
latest main branch of dashboard

**OpenShift Version**
Version #: 
Provider (Baremetal, OpenStack, RHV, AWS, OKD, CodeReady Containers, ...):

**Additional context**

**Comment by andrewballantyne** [comment]
Storage classes are not yet supported. There is a workaround for the Jupyter tile to use the one from the DashboardConfig, but they are not supported in DS Projects today. See https://github.com/opendatahub-io/odh-dashboard/issues/1270 for the feature work behind supporting it. Hopefully the UX files are reachable by non-shared-with people... we are still working out permission based stuff.

**Comment by shalberd** [comment]
@andrewballantyne did not realize their are efforts underway, closing, thank you. Regarding permissons, I'd only let ClusterRole Admin type users create PVCs, but listing available storageclasses to pick from querying the cluster api should be possible might not be possible for Admin at project level, even though populating that list of storageclasses to pick from would be cool to have.
