### ISSUE TITLE
Add KServe manifests to the repo

### ISSUE THREAD

**Issue by danielezonca** [opendatahub-io/odh-manifests#848]
This ticket is part of the tracking ticket to include KServe into ODH
- https://github.com/opendatahub-io/opendatahub-community/issues/54

The scope of this ticket is to add the necessary bits into the manifest repo to enable the usage of KServe via KfDef

**Comment by danielezonca** [comment]
Fix for the issue https://github.com/opendatahub-io/odh-manifests/pull/838

**Comment by heyselbi** [comment]
https://github.com/opendatahub-io/odh-manifests/pull/838

**Comment by heyselbi** [comment]
https://github.com/opendatahub-io/kserve/pull/14

**Comment by israel-hdez** [comment]
PR for release-0.11: https://github.com/opendatahub-io/kserve/pull/16
