### ISSUE TITLE
[Jupyterhub] Image availability in Jupyterhub using naming relies on imagestream name

### ISSUE THREAD

**Issue by 4n4nd** [opendatahub-io/odh-manifests#86]
Only Imagestreams with names like `s2i-*-notebook` are available in Jupyterhub, is there any way to configure this?

**Comment by vpavlin** [comment]
Yes, in the latest version of ODH the images are loaded based on labels - https://github.com/vpavlin/jupyterhub-singleuser-profiles/#notebook-images

e.g. https://github.com/opendatahub-io/odh-manifests/blob/master/jupyterhub/notebook-images/overlays/additional/tensorflow-notebook-imagestream.yaml#L5

**Comment by 4n4nd** [comment]
Oh awesome. By latest you mean odh version >= 0.6?
thanks!

**Comment by vpavlin** [comment]
Yes, >=0.6.0

**Comment by 4n4nd** [comment]
UPDATE: I think this might work in odh v0.5.1
