### ISSUE TITLE
Add kustomize patch to remove `Namespace` created by kserve

### ISSUE THREAD

**Issue by VaishnaviHire** [opendatahub-io/odh-manifests#884]
**Describe the bug**
kserve[ creates namespace](https://github.com/opendatahub-io/odh-manifests/blob/master/kserve/kserve-built/kserve-built.yaml#L2) object which is not required for ODH deployment. Add patch that removes the namespace creation [similar to other components](https://github.com/opendatahub-io/odh-manifests/blob/master/odh-notebook-controller/kf-notebook-controller/overlays/openshift/remove_namespace_patch.yaml).

**Comment by taneem-ibrahim** [comment]
@israel-hdez could you please put an estimated start and end date?
