### ISSUE TITLE
Exclude KServe Alibi and art-explainer images and usages

### ISSUE THREAD

**Issue by danielezonca** [opendatahub-io/odh-manifests#885]
**Is your feature request related to a problem? Please describe.**
We don't need alibi and art-explainer in Kserve for now so we should exclude the usage from the manifests (and stop producing the images)

**Describe the solution you'd like**
It should be possible to apply KServe manifests without having alibi and art-explainer images

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by taneem-ibrahim** [comment]
@israel-hdez could you please put an estimated start and end date?

**Comment by israel-hdez** [comment]
I'm starting today, together with #884. Complexity 1. I should have a PR, also today. Although, setting end date for Monday to allow room for peer review.
